% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Tölfræði fyrir almenning},
  pdfauthor={Sigurbjörg Anna Guðnadóttir},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{Tölfræði fyrir almenning}
\author{Sigurbjörg Anna Guðnadóttir}
\date{2020-08-18}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
Þeir pakkar sem við notum eru:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(survival)}
\KeywordTok{library}\NormalTok{(flexsurv)}
\KeywordTok{library}\NormalTok{(survminer)}
\KeywordTok{library}\NormalTok{(arsenal)}
\KeywordTok{library}\NormalTok{(table1)}
\end{Highlighting}
\end{Shaded}

\hypertarget{reg}{%
\chapter{Línuleg aðhvarfsgreining}\label{reg}}

Í línulegri aðhvarfsgreiningu gildir að útkoman þarf að vera línuleg breyta. Það gildir ekki um skýribreyturnar.

Þeir pakkar sem við notum eru:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(epitools)}
\KeywordTok{library}\NormalTok{(arsenal)}
\KeywordTok{library}\NormalTok{(ggpubr)}
\KeywordTok{library}\NormalTok{(table1)}
\end{Highlighting}
\end{Shaded}

\hypertarget{luxfdsandi-tuxf6lfruxe6uxf0i}{%
\section{Lýsandi tölfræði}\label{luxfdsandi-tuxf6lfruxe6uxf0i}}

Western Collaborative Group Study (WCGS) gagnasafnið er í epitools- pakkanum. Gagnasafnið byggir á rannsókn sem var með meginmarkmið að skoða tengsl persónuleikagerðar og hjartasjúkdóma. Viðfangsefnin voru 3154 karlmenn á aldrinum 39 - 59 ára, þeim var fylgt eftir í allt að 10 ár þangað til þeir fengu hjartasjúkdóm, létust, þeir urðu 70 ára eða eftirfylgni lauk af öðrum ástæðum. Viðfangsefnin komu inn í rannsóknina á árunum 1960-1961. Í þessum kafla og næstu ætlum við að skoða tengsl kólesteróls og reykinga.

\hypertarget{suxe6kjum-guxf6gnin-og-luxf6gum-til}{%
\subsection{Sækjum gögnin og lögum til}\label{suxe6kjum-guxf6gnin-og-luxf6gum-til}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{data}\NormalTok{(wcgs)}
\NormalTok{wcgs <{-}}\StringTok{ }\KeywordTok{as\_tibble}\NormalTok{(wcgs)}

\NormalTok{wcgs <{-}}\StringTok{ }\NormalTok{wcgs }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{agec =}\NormalTok{ age0 }\OperatorTok{{-}}\StringTok{ }\DecValTok{46}\NormalTok{,}
         \DataTypeTok{cholmmol =}\NormalTok{ chol0 }\OperatorTok{/}\StringTok{ }\DecValTok{39}\NormalTok{,}
         \DataTypeTok{sbp10 =}\NormalTok{ sbp0 }\OperatorTok{/}\StringTok{ }\DecValTok{10}\NormalTok{,}
         \DataTypeTok{dibpat =} \KeywordTok{factor}\NormalTok{(dibpat0, }\DataTypeTok{levels =} \DecValTok{0}\OperatorTok{:}\DecValTok{1}\NormalTok{, }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{, }\StringTok{"A"}\NormalTok{)),}
         \DataTypeTok{smoker =} \KeywordTok{factor}\NormalTok{(}\DecValTok{1} \OperatorTok{*}\StringTok{ }\NormalTok{(ncigs0 }\OperatorTok{>}\StringTok{ }\DecValTok{0}\NormalTok{), }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{, }\StringTok{"Yes"}\NormalTok{)), }\CommentTok{\# ATH, sé til hvort ég nota}
         \DataTypeTok{bmi =}\NormalTok{ (weight0 }\OperatorTok{*}\StringTok{ }\FloatTok{0.454}\NormalTok{) }\OperatorTok{/}\StringTok{ }\NormalTok{((height0 }\OperatorTok{*}\StringTok{ }\FloatTok{2.54}\NormalTok{)}\OperatorTok{/}\DecValTok{100}\NormalTok{)}\OperatorTok{\^{}}\DecValTok{2}\NormalTok{,}
         \DataTypeTok{bmiq3 =} \KeywordTok{cut}\NormalTok{(bmi, }\DataTypeTok{breaks =} \KeywordTok{quantile}\NormalTok{(bmi, }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\OperatorTok{/}\DecValTok{3}\NormalTok{)), }\CommentTok{\# ATH, veit ekki hvort ég held þessu}
                     \DataTypeTok{include.lowest =}\NormalTok{ T, }\DataTypeTok{right =}\NormalTok{ F)}
\NormalTok{  )}

\NormalTok{wcgs\_dat <{-}}\StringTok{ }\NormalTok{wcgs }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(id, agec, cholmmol, sbp10, ncigs0, dibpat, bmi, arcus0) }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{complete.cases}\NormalTok{(.)) }

\NormalTok{wcgs\_dat}\OperatorTok{$}\NormalTok{dibpat <{-}}\StringTok{ }\KeywordTok{relevel}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{dibpat, }\StringTok{"A"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Við búum til nýja aldursbreytu þar sem við erum búin að staðla hana m.v. meðaldurinn í hópnum. Meðalaldurinn er 46.28 og drögum við þvi 46 frá aldrinum. Það mun auðvelda túlkun á líkönum.\\
!!! ATH af hverju deilum við með 10 og 39?.\\
Breytan dibpat0 eru persónuleikagerðirnar, við setjum hana sem flokkabreytu (e. factor).\\
Til þess að reikna BMI þá þurfum við að breyta hæðinni í metra og þyngdinni í kíló. Útbúum einnig flokkabreytu fyrir bmi þar sem við skiptum henni í 3 jafna hluta.

Í þessari úrvinnslu notum við bara þá einstaklinga sem hafa allar breyturnar sem við ætlum að skoða, aðra fjarlægjum við úr gagnasafninu.

Gott er að setja ``label'' á breyturnar til að hafa íslensku í gröfum og öðrum myndum. Notum til þess skipunina \(label\) úr pakkanum \(arsenal\)

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{cholmmol) <{-}}\StringTok{ "Kólesteról"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{agec) <{-}}\StringTok{ "Miðjaður Aldur"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{bmi) <{-}}\StringTok{ "BMI"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{dibpat) <{-}}\StringTok{ "Hegðunarhópur"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{sbp10) <{-}}\StringTok{ "Blóðþrýstingur"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0) <{-}}\StringTok{ "Fjöldi sígaréttna"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{arcus0) <{-}}\StringTok{ "Arcus"}  \CommentTok{\# ATH!!! Hvað er arcus?}
\end{Highlighting}
\end{Shaded}

Mikilvægt skref í allri tölfræðiúrvinnslu er hreinsun gagnanna, t.d. skoða hvort öll gildi séu eðlileg. Við gerum það ekki hérna en við skoðum töflu 1, helstu lýsistærðir og dreifingu gagnanna.

\hypertarget{dreifing-helstu-breytna}{%
\subsection{Dreifing helstu breytna}\label{dreifing-helstu-breytna}}

Skoðum dreifingu þeirra breytna sem við höfum mestan áhuga á, það er kólesteról og reykingar. Gott getur verið að skoða skýribreyturnar á svipaðan hátt. Við gerð grafa notum við skipanir úr pakkanum \(tidyverse\), einnig notum við skipunina \(ggarrange\) úr pakkanum \(ggpubr\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kol <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{mapping =} \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ cholmmol)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_bar}\NormalTok{(}\DataTypeTok{fill=}\DecValTok{4}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Kólesteról"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{\textquotesingle{}Kólesteról\textquotesingle{}}\NormalTok{, }\DataTypeTok{y=}\StringTok{\textquotesingle{}Count\textquotesingle{}}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme\_bw}\NormalTok{()}

\NormalTok{reyk <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{mapping =} \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ ncigs0)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_bar}\NormalTok{(}\DataTypeTok{fill=}\DecValTok{4}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Reykingar"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{\textquotesingle{}Reykingar\textquotesingle{}}\NormalTok{, }\DataTypeTok{y=}\StringTok{\textquotesingle{}Count\textquotesingle{}}\NormalTok{) }\OperatorTok{+}\StringTok{  }
\StringTok{  }\KeywordTok{theme\_bw}\NormalTok{()}

\KeywordTok{ggarrange}\NormalTok{(kol, reyk,}\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{, }\DataTypeTok{nrow=}\DecValTok{1}\NormalTok{) }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{annotate\_figure}\NormalTok{(}
    \DataTypeTok{top =} \KeywordTok{text\_grob}\NormalTok{(}\StringTok{"Dreifing útkomu og útsetningar"}\NormalTok{,}\DataTypeTok{face =} \StringTok{"bold"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{14}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-6-1.pdf}

Oft er líka áhugavert að skoða hvernig fjórðungsmörkin eru fyrir breyturnar.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qu\_chol <{-}}\StringTok{ }\KeywordTok{quantile}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{cholmmol)}
\NormalTok{qu\_chol }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        0%       25%       50%       75%      100% 
##  2.641026  5.051282  5.717949  6.487179 16.538462
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qu\_cig <{-}}\StringTok{ }\KeywordTok{quantile}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0)}
\NormalTok{qu\_cig}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   0%  25%  50%  75% 100% 
##    0    0    0   20   99
\end{verbatim}

Hérna sést t.d. að 50\% karlmannanna er með kólesteról á bílinu 5.05 til 6.49. Einnig að langflestir reykja ekki, en 25\% af karlmönnum reykja 20 sígaréttur eða meira.

\hypertarget{tafla-1}{%
\subsection{Tafla 1}\label{tafla-1}}

ATH!!! Vantar text um tilgang töflu 1.
ATH!!! Myndum við vilja hafa aðra breytu efst.
Í töflu 1 þá verður breytan sem er í hausnum að vera flokkabreyta, ef breytan sem við viljum skipta hópnum eftir er ekki flokkabreyta þá er hægt að útbúa hana með einhvers konar bilskiptingu. Hérna prófum við að skipta að kólestrólinu með fjórðungsmörkunum. Aðrar breytur geta verið hvort sem er flokkabreytur eða samfelldar.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wcgs\_dat <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{chol\_q =} \KeywordTok{cut}\NormalTok{(cholmmol, }\DataTypeTok{breaks =} \KeywordTok{quantile}\NormalTok{(cholmmol, }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\OperatorTok{/}\DecValTok{4}\NormalTok{)), }
                      \DataTypeTok{include.lowest =}\NormalTok{ T, }\DataTypeTok{right =}\NormalTok{ F))}
\end{Highlighting}
\end{Shaded}

Til eru ýmsir skipanir til þess að gera töflu 1, sú sem við notum hérna er \(tableby\) úr pakkanum \(arsenal\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tab\_wcgs <{-}}\StringTok{ }\KeywordTok{tableby}\NormalTok{(chol\_q }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{ncigs0 }\OperatorTok{+}\StringTok{ }\NormalTok{agec }\OperatorTok{+}\StringTok{ }\NormalTok{bmi }\OperatorTok{+}\StringTok{ }\NormalTok{dibpat }\OperatorTok{+}\StringTok{ }\NormalTok{sbp10 }\OperatorTok{+}\StringTok{ }\NormalTok{arcus0, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\KeywordTok{summary}\NormalTok{(tab\_wcgs)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lcccccr@{}}
\toprule
\begin{minipage}[b]{0.17\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\centering
{[}2.64,5.05) (N=775)\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\centering
{[}5.05,5.72) (N=776)\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\centering
{[}5.72,6.49) (N=802)\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\centering
{[}6.49,16.5{]} (N=787)\strut
\end{minipage} & \begin{minipage}[b]{0.10\columnwidth}\centering
Total (N=3140)\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
p value\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.17\columnwidth}\raggedright
\textbf{Fjöldi sígaréttna}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\textless{} 0.001\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Mean (SD)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
9.819 (13.651)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
10.781 (14.433)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
12.399 (14.939)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
13.255 (14.679)\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
11.577 (14.494)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Range\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 60.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 80.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 99.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 70.000\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
0.000 - 99.000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
\textbf{Miðjaður Aldur}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\textless{} 0.001\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Mean (SD)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
-0.466 (5.360)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
-0.179 (5.475)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.677 (5.528)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
1.041 (5.574)\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
0.275 (5.517)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Range\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
-7.000 - 13.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
-7.000 - 13.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
-7.000 - 13.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
-7.000 - 13.000\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
-7.000 - 13.000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
\textbf{BMI}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\textless{} 0.001\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Mean (SD)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
24.339 (2.697)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
24.333 (2.592)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
24.747 (2.526)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
24.730 (2.420)\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
24.540 (2.567)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Range\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
11.202 - 38.986\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
15.676 - 37.267\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
16.889 - 35.763\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
17.737 - 35.735\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
11.202 - 38.986\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
\textbf{Hegðunarhópur}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.030\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~A\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
359 (46.3\%)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
387 (49.9\%)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
416 (51.9\%)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
421 (53.5\%)\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
1583 (50.4\%)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~B\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
416 (53.7\%)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
389 (50.1\%)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
386 (48.1\%)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
366 (46.5\%)\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
1557 (49.6\%)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
\textbf{Blóðþrýstingur}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\textless{} 0.001\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Mean (SD)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
12.624 (1.430)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
12.726 (1.420)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
12.964 (1.540)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
13.120 (1.575)\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
12.860 (1.506)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Range\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
9.800 - 21.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
10.000 - 21.200\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
10.000 - 20.800\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
10.000 - 23.000\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
9.800 - 23.000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
\textbf{Arcus}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\textless{} 0.001\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Mean (SD)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.226 (0.418)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.277 (0.448)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.323 (0.468)\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.367 (0.482)\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
0.299 (0.458)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.17\columnwidth}\raggedright
~~~Range\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 1.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 1.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 1.000\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\centering
0.000 - 1.000\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering
0.000 - 1.000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

Ýmsar leiðir eru til að skoða gögnin frekar og ætlum við að sýna nokkur dæmi um það, en það er alls ekki tæmandi listi og oft gott að gera fyrir fleiri breytur en við gerum hérna.

Skoðum myndrænt meðaltal og staðalfrávik fjölda sígaréttna út frá kólestrólhópum. Það gerum við með ``boxplotti''.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(chol\_q),  }\DataTypeTok{y=}\NormalTok{ncigs0, }\DataTypeTok{fill=}\KeywordTok{as.factor}\NormalTok{(chol\_q))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_boxplot}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{\textquotesingle{}Kólesteról\textquotesingle{}}\NormalTok{, }\DataTypeTok{y=}\StringTok{\textquotesingle{}Sígaréttufjöldi\textquotesingle{}}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Kólestról og reykingar"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme\_bw}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-10-1.pdf}
Við sjáum að meðaltal hækkar í seinni tveimur hópunum en staðalfrávikin virðast svipuð.

Stundum er gott að sjá hvort það séu einhver víxláhrif á milli breytna. Skoðum því hvort áhrif sígaréttna á kólestról sé eins hjá hegðunarhópunum tveimur. Hérna notum við upphaflegu samfelldu kólesteról breytuna en skiptum sígaréttureykingum í 3 flokka: Reykja ekki, 1 pakki, meira en einn pakki.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wcgs\_dat <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{ncigs0\_3 =} \KeywordTok{ifelse}\NormalTok{(ncigs0 }\OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{, }\StringTok{"Reyklaus"}\NormalTok{,}\KeywordTok{ifelse}\NormalTok{(ncigs0 }\OperatorTok{<=}\DecValTok{20}\NormalTok{,}\StringTok{"1 pakki"}\NormalTok{,}\StringTok{"Meira"}\NormalTok{)))}

\CommentTok{\# Endurröðum}
\NormalTok{wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0\_}\DecValTok{3}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0\_}\DecValTok{3}\NormalTok{)}
\NormalTok{wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0\_}\DecValTok{3}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{relevel}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0\_}\DecValTok{3}\NormalTok{,}\StringTok{"1 pakki"}\NormalTok{)}
\NormalTok{wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0\_}\DecValTok{3}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{relevel}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{ncigs0\_}\DecValTok{3}\NormalTok{,}\StringTok{"Reyklaus"}\NormalTok{)}

\NormalTok{wcgs\_dat  }\OperatorTok{\%>\%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{fill=}\DecValTok{4}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ ncigs0\_}\DecValTok{3}\NormalTok{, }\DataTypeTok{color =}\NormalTok{ dibpat, }\DataTypeTok{group =}\NormalTok{ dibpat, }\DataTypeTok{y =}\NormalTok{ cholmmol) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{\textquotesingle{}Fjöldi sígaréttna\textquotesingle{}}\NormalTok{, }\DataTypeTok{y=}\StringTok{\textquotesingle{}Kólesteról\textquotesingle{}}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{stat\_summary}\NormalTok{(}\DataTypeTok{fun =}\NormalTok{ mean, }\DataTypeTok{geom =} \StringTok{"point"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{stat\_summary}\NormalTok{(}\DataTypeTok{fun =}\NormalTok{ mean, }\DataTypeTok{geom =} \StringTok{"line"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Kólesteról og reykingar"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{color =} \StringTok{"Hegðunarhópur"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-11-1.pdf}
Sjáum að hóparnir tveir koma ekki alveg eins út. Um þá sem reykja ekki gildir að, þeir sem eru í hegðunarhópi A er kólesterólið mun hærra en þegar við skoðum þá sem reykja 1 pakka á dag eða minna þá minnkar munurinn. Svo frá einum pakka og yfir í meira þá stendur hópur B í stað en hópur A hækkar og bilið á milli þeirra eykst. Svo víxláhrif virðast til staðar.

\hypertarget{luxedkanageruxf0}{%
\section{Líkanagerð}\label{luxedkanageruxf0}}

\hypertarget{emmeans}{%
\section{Emmeans}\label{emmeans}}

\hypertarget{tvuxedkosta-auxf0hvarfsgreining}{%
\chapter{Tvíkosta aðhvarfsgreining}\label{tvuxedkosta-auxf0hvarfsgreining}}

\hypertarget{lif}{%
\chapter{Lifunargreining}\label{lif}}

Í þessum kafla munun við styðjast við Western Collaborative Group Study (WCGS) gagnasafnið sem er í epitools- pakkanum. Þetta eru gögn úr rannsókn þar sem meginmarkmið hennar var að skoða tengsl persónuleikagerðar og hjartasjúkdóma og því eru hjartasjúkdómar aðalútkomubreytan okkar. Viðfangsefnin voru 3154 karlmenn á aldrinum 39 - 59 ára, þeim var fylgt eftir í allt að 10 ár þangað til þeir fengu hjartasjúkdóm, eða létust, eða þeir urðu 70 ára eða eftirfylgni lauk af öðrum ástæðum. Viðfangsefnin komu inn í rannsóknina á árunum 1960-1961.

Við ætlum að skoða áhrif mismunandi persónuleikagerða A og B á hjartaáföll með og án skýribreytna. A og B flokkunin vísar í hvernig fólk meðhöndlar streitu og álag. Þeir sem eru í A hópi eru með meira keppnisskap, óþolinmóðari og árásagjarnari en þeir sem eru í hópi B. Þær skýribreytur sem við munum skoða eru aldur, magn kólesteról í blóði, blóðþrýstings, reykinga og BMI stuðull.

\hypertarget{lif_skod}{%
\section{Skoðun lifunargagna}\label{lif_skod}}

\hypertarget{suxe6kjum-guxf6gnin-og-luxf6gum-til-1}{%
\subsection{Sækjum gögnin og lögum til}\label{suxe6kjum-guxf6gnin-og-luxf6gum-til-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{data}\NormalTok{(wcgs,}\DataTypeTok{package =} \StringTok{"epitools"}\NormalTok{)}
\NormalTok{wcgs <{-}}\StringTok{ }\KeywordTok{as\_tibble}\NormalTok{(wcgs)}

\NormalTok{wcgs <{-}}\StringTok{ }\NormalTok{wcgs }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{surv\_time\_y =}\NormalTok{ time169 }\OperatorTok{/}\StringTok{ }\FloatTok{365.24}\NormalTok{,}
         \DataTypeTok{agec =}\NormalTok{ age0 }\OperatorTok{{-}}\StringTok{ }\DecValTok{46}\NormalTok{,}
         \DataTypeTok{cholmmol =}\NormalTok{ chol0 }\OperatorTok{/}\StringTok{ }\DecValTok{39}\NormalTok{,}
         \DataTypeTok{sbp10 =}\NormalTok{ sbp0 }\OperatorTok{/}\StringTok{ }\DecValTok{10}\NormalTok{,}
         \DataTypeTok{dibpat =} \KeywordTok{factor}\NormalTok{(dibpat0, }\DataTypeTok{levels =} \DecValTok{0}\OperatorTok{:}\DecValTok{1}\NormalTok{, }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{, }\StringTok{"A"}\NormalTok{)),}
         \DataTypeTok{smoker =} \KeywordTok{factor}\NormalTok{(}\DecValTok{1} \OperatorTok{*}\StringTok{ }\NormalTok{(ncigs0 }\OperatorTok{>}\StringTok{ }\DecValTok{0}\NormalTok{), }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{, }\StringTok{"Yes"}\NormalTok{)),}
         \DataTypeTok{bmi =}\NormalTok{ (weight0 }\OperatorTok{*}\StringTok{ }\FloatTok{0.454}\NormalTok{) }\OperatorTok{/}\StringTok{ }\NormalTok{((height0 }\OperatorTok{*}\StringTok{ }\FloatTok{2.54}\NormalTok{)}\OperatorTok{/}\DecValTok{100}\NormalTok{)}\OperatorTok{\^{}}\DecValTok{2}\NormalTok{,}
         \DataTypeTok{bmiq3 =} \KeywordTok{cut}\NormalTok{(bmi, }\DataTypeTok{breaks =} \KeywordTok{quantile}\NormalTok{(bmi, }\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\OperatorTok{/}\DecValTok{3}\NormalTok{)),}
                       \DataTypeTok{include.lowest =}\NormalTok{ T, }\DataTypeTok{right =}\NormalTok{ F)}
\NormalTok{         )}
\NormalTok{wcgs\_dat <{-}}\StringTok{ }\NormalTok{wcgs }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(id, }\DataTypeTok{surv\_time =}\NormalTok{ time169, surv\_time\_y, }\DataTypeTok{status=}\NormalTok{chd69,  agec, cholmmol, sbp10, smoker, dibpat, bmi,bmiq3, arcus0) }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{complete.cases}\NormalTok{(.)) }\OperatorTok{\%>\%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{statusf=}\KeywordTok{factor}\NormalTok{(status,}\DataTypeTok{levels=}\DecValTok{0}\OperatorTok{:}\DecValTok{1}\NormalTok{,}\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"No event"}\NormalTok{,}\StringTok{"Yes event"}\NormalTok{)))}

\NormalTok{wcgs\_dat}\OperatorTok{$}\NormalTok{dibpat <{-}}\StringTok{ }\KeywordTok{relevel}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{dibpat, }\StringTok{"A"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Tíminn time169 er í dögum en við reiknum nýja breytu sem mælir tímann í árum.\\
Við búum til nýja aldursbreytu þar sem við erum búin að staðla hana m.v. meðaldurinn í hópnum. Meðalaldurinn er 46.28 og drögum við þvi 46 frá aldrinum. Það mun auðvelda túlkun á líkönum.\\
!!! ATH af hverju deilum við með 10 og 39?.\\
Breytan dibpat0 eru persónuleikagerðirnar, við setjum hana sem flokkabreytu (e. factor).\\
Við skilgreinum reykingamann þann sem reykir amk 1 sígaréttu á dag og höfum breytuna sem flokkabreytu.\\
Til þess að reikna BMI þá þurfum við að breyta hæðinni í metra og þyngdinni í kíló. Útbúum einnig flokkabretytu fyrir bmi þar sem við skiptum henni í 3 jafna hluta.
Breytan chd69 segir til um hvort karlmennirnir fengu hjartasjúkdóm eða ekki og setjum við hana því sem ``status'', það hvort atburður hafi átt sér stað eða ekki er oft kallað ``status''.

Við notum bara þá einstaklinga sem hafa allar breyturnar sem við ætlum að skoða, aðra fjarlægjum við úr gagnasafninu.

\hypertarget{tuxf6kum-luxe9tta-skouxf0un-uxe1-guxf6gnunum}{%
\subsection{Tökum létta skoðun á gögnunum}\label{tuxf6kum-luxe9tta-skouxf0un-uxe1-guxf6gnunum}}

Fyrsta skrefið er alltaf að skoða gögnin og sjá hvað einfaldur reikningur gefur okkur. Við skoðum gögnin miða við ár sem tímalengd.

\emph{Helstu tölur}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Hversu margir eru í safninu og í hvorum hópi fyrir sig?}
\NormalTok{rownames <{-}}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Allir"}\NormalTok{, }\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{)}
\NormalTok{fj\_t <{-}}\StringTok{ }\KeywordTok{dim}\NormalTok{(wcgs\_dat)[}\DecValTok{1}\NormalTok{]}
\NormalTok{fj\_g <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{group\_by}\NormalTok{(dibpat) }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{()}

\NormalTok{fj <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(fj\_t,fj\_g[[}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{]],fj\_g[[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]])}

\CommentTok{\# Hversu margir fengu hjartaáfall í heildina og í hvorum hópi fyrir sig?}

\NormalTok{st\_t <{-}}\StringTok{ }\KeywordTok{sum}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{status)}
\NormalTok{st\_g <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{group\_by}\NormalTok{(dibpat) }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{tidni =} \KeywordTok{sum}\NormalTok{(status))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` ungrouping output (override with `.groups` argument)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{st <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(st\_t,st\_g[[}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{]],st\_g[[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]])}

\CommentTok{\# Hver er eftirfylgnitíminn og lambda fyrir all hópana?}

\NormalTok{ef\_t <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{sum\_time =} \KeywordTok{sum}\NormalTok{(surv\_time\_y),}\DataTypeTok{lambda =} \KeywordTok{sum}\NormalTok{(status) }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(surv\_time\_y))}

\NormalTok{ef\_g <{-}}\StringTok{ }\NormalTok{wcgs\_lambda <{-}}\StringTok{ }\NormalTok{wcgs\_dat }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{group\_by}\NormalTok{(dibpat) }\OperatorTok{\%>\%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{sum\_time =} \KeywordTok{sum}\NormalTok{(surv\_time\_y),}\DataTypeTok{lambda =} \KeywordTok{sum}\NormalTok{(status) }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(surv\_time\_y))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` ungrouping output (override with `.groups` argument)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ef <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{round}\NormalTok{(ef\_t[[}\DecValTok{1}\NormalTok{]],}\DecValTok{2}\NormalTok{), }\KeywordTok{round}\NormalTok{(ef\_g[[}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{]],}\DecValTok{2}\NormalTok{), }\KeywordTok{round}\NormalTok{(ef\_g[[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]],}\DecValTok{2}\NormalTok{))}
\NormalTok{lambda <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{round}\NormalTok{(ef\_t[[}\DecValTok{2}\NormalTok{]],}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(ef\_g[[}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{]],}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(ef\_g[[}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{]],}\DecValTok{4}\NormalTok{))}

\CommentTok{\# Setjum í eina töflu}
\NormalTok{stats <{-}}\StringTok{ }\KeywordTok{as\_tibble}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(rownames,fj,st,ef,lambda))}

\CommentTok{\# !!! ATH betra útlit}
\NormalTok{stats <{-}stats }\OperatorTok{\%>\%}\StringTok{ }\KeywordTok{rename}\NormalTok{( Hópar=}\StringTok{ }\NormalTok{rownames, Heildarfjöldi =}\StringTok{ }\NormalTok{V2,  }\DataTypeTok{Tilfelli =}\NormalTok{ V3, Eftirfylgnitími =}\StringTok{ }\NormalTok{V4, }\DataTypeTok{lambda =}\NormalTok{ V5)}
\NormalTok{stats}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 5
##   Hópar Heildarfjöldi Tilfelli Eftirfylgnitími lambda
##   <chr> <chr>         <chr>    <chr>           <chr> 
## 1 Allir 3140          255      23072.54        0.0111
## 2 A     1583          177      11330.47        0.0156
## 3 B     1557          78       11742.07        0.0066
\end{verbatim}

Eftirfylgnitíminn er sá tími sem einstaklingur er í rannsókninni, hámark 10 ár í þessari rannsókn. Lambda er fjöldi atburða á tímaeiningu, í þessu tilfelli er það eitt ár. Svo 0.0111 eða 1.11 \% er eins árs meðaláhætta fyrir heildarhópinn.

\emph{Áhættuhlutfallið}
Áhættuhlutfallið er hlutfallið af líkunum á því að atburðurinn gerist í meðferðarhópnum á móti líkunum á því að atburðurinn gerist í viðmiðunarhópnum. Við lítum á persónuleikagerð A sem meðferðarhópinn og persónuleikagerð B sem viðmiðunarhópinn.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hz <{-}}\StringTok{ }\NormalTok{wcgs\_lambda}\OperatorTok{$}\NormalTok{lambda[}\DecValTok{2}\NormalTok{]}\OperatorTok{/}\NormalTok{wcgs\_lambda}\OperatorTok{$}\NormalTok{lambda[}\DecValTok{1}\NormalTok{] }
\end{Highlighting}
\end{Shaded}

Áhættuhlutfallið er 0.43 og því er einstaklingur með persónuleikagerð A í -57\% meiri áhættu til að fá hjartaáfall ef allir aðrir þættir eru eins.

Af þessum gildum höfum við mestan áhuga áhættunni (þ.e. lambda) fyrir hvora persónuleikagerð fyrir sig og áhættuhlutfallinu. Fallið \(flexsurvreg\) úr pakkanum \(flexsurv\) hentar vel til þess að reikna það. Einnig notum við fallið \(Surv\) úr pakkanum \(survival\).\\
Fallið \(Surv\) er notað til að útbúa breytu af gerðinni lifunarhlutur (e. survival object). Það tekur inn í sig tvær breytur; annars vegar hversu langur tími leið fram að atburði eða skerðingu og hins vegar hvort atburður eða skerðing átti stað á þeim tímapunkti. Þeir sem hafa ekki fengið hjartaáfall eru með skerðingu.

Líkanið sem við köllum VL\_O er notað til að reikna lambda fyrir allan hópinn en VL\_1 til þess að reikna lambda fyrir hópa A og B.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{VL\_}\DecValTok{0}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{flexsurvreg}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time\_y, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\DecValTok{1}\NormalTok{,}\DataTypeTok{data=}\NormalTok{wcgs\_dat,}\DataTypeTok{dist=}\StringTok{"exponential"}\NormalTok{)}
\NormalTok{VL\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{flexsurvreg}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time\_y, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{dibpat,}\DataTypeTok{data=}\NormalTok{wcgs\_dat,}\DataTypeTok{dist=}\StringTok{"exponential"}\NormalTok{)}

\NormalTok{lambda\_}\DecValTok{0}\NormalTok{ <{-}}\StringTok{ }\NormalTok{VL\_}\DecValTok{0}\OperatorTok{$}\NormalTok{res[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]}
\NormalTok{lambda\_a <{-}}\StringTok{ }\NormalTok{VL\_}\DecValTok{1}\OperatorTok{$}\NormalTok{res[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }
\NormalTok{lambda\_b <{-}}\StringTok{ }\KeywordTok{exp}\NormalTok{(VL\_}\DecValTok{1}\OperatorTok{$}\NormalTok{res[}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{]}\OperatorTok{+}\KeywordTok{log}\NormalTok{(VL\_}\DecValTok{1}\OperatorTok{$}\NormalTok{res[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{])) }


\NormalTok{lambda\_}\DecValTok{2}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{round}\NormalTok{(lambda\_}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(lambda\_a,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(lambda\_b,}\DecValTok{4}\NormalTok{))}

\CommentTok{\# Setjum í eina töflu}
\NormalTok{stats2 <{-}}\StringTok{ }\KeywordTok{as\_tibble}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(rownames, lambda, lambda\_}\DecValTok{2}\NormalTok{))}

\CommentTok{\# !!! ATH betra útlit}
\NormalTok{stats2 <{-}}\StringTok{ }\NormalTok{stats2 }\OperatorTok{\%>\%}\StringTok{ }\KeywordTok{rename}\NormalTok{( Hópar=}\StringTok{ }\NormalTok{rownames, Lambda\_handreiknað =}\StringTok{ }\NormalTok{V2,  Lambda\_með}\DataTypeTok{\_falli =}\NormalTok{ V3)}
\NormalTok{stats2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 3
##   Hópar Lambda_handreiknað Lambda_með_falli
##   <chr> <chr>              <chr>           
## 1 Allir 0.0111             0.0111          
## 2 A     0.0156             0.0156          
## 3 B     0.0066             0.0066
\end{verbatim}

Getum líka reiknað áhættuhlutfallið

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hz\_}\DecValTok{2}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{exp}\NormalTok{(VL\_}\DecValTok{1}\OperatorTok{$}\NormalTok{res[}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

Áhættuhlutfallið er 0.43 sem er það sama og við fengum með handreikningi.

\hypertarget{tafla-1-1}{%
\section{Tafla 1}\label{tafla-1-1}}

Þar sem við gerum yfirleitt líkön með skýribreytum þá er gott að útbúa töflu 1 til þess að fá tilfinningu fyrir dreifingu þeirra. Til eru ýmsar skipanir til að gera þessa töflu, meðal annars \(tableyby\) í pakkanum \(arsenal\). Gott er að nefna breyturnar fyrst með skiljanlegum heitum. Notum til þess \(label\) úr pakkanum table1

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{dibpat) <{-}}\StringTok{ "Hegðunarhópur"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{agec) <{-}}\StringTok{ "Aldur"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{cholmmol) <{-}}\StringTok{ "Kólestról"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{sbp10) <{-}}\StringTok{ "Blóðþrýstingur"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{smoker) <{-}}\StringTok{ "Reykingar"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{bmi) <{-}}\StringTok{ "BMI"}
\KeywordTok{label}\NormalTok{(wcgs\_dat}\OperatorTok{$}\NormalTok{arcus0) <{-}}\StringTok{ "Hornhimnubogi"} \CommentTok{\#\# !!! ATH er þetta rétt íslenska?}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tab1 <{-}}\StringTok{ }\KeywordTok{tableby}\NormalTok{(dibpat }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{bmi }\OperatorTok{+}\StringTok{ }\NormalTok{agec }\OperatorTok{+}\StringTok{ }\NormalTok{cholmmol }\OperatorTok{+}\StringTok{ }\NormalTok{sbp10 }\OperatorTok{+}\StringTok{ }\NormalTok{smoker }\OperatorTok{+}\StringTok{ }\NormalTok{bmi }\OperatorTok{+}\StringTok{ }\NormalTok{arcus0, }\DataTypeTok{data=}\NormalTok{ wcgs\_dat)}
\KeywordTok{summary}\NormalTok{(tab1, }\DataTypeTok{text =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 
## |               |   A (N=1583)    |   B (N=1557)    | Total (N=3140)  | p value|
## |:--------------|:---------------:|:---------------:|:---------------:|-------:|
## |BMI            |                 |                 |                 |   0.130|
## |-  Mean (SD)   | 24.609 (2.600)  | 24.470 (2.531)  | 24.540 (2.567)  |        |
## |-  Range       | 11.202 - 37.285 | 15.676 - 38.986 | 11.202 - 38.986 |        |
## |Aldur          |                 |                 |                 | < 0.001|
## |-  Mean (SD)   |  0.769 (5.697)  | -0.228 (5.282)  |  0.275 (5.517)  |        |
## |-  Range       | -7.000 - 13.000 | -7.000 - 13.000 | -7.000 - 13.000 |        |
## |Kólestról      |                 |                 |                 |   0.001|
## |-  Mean (SD)   |  5.867 (1.135)  |  5.740 (1.088)  |  5.804 (1.113)  |        |
## |-  Range       | 2.641 - 16.538  | 2.821 - 10.256  | 2.641 - 16.538  |        |
## |Blóðþrýstingur |                 |                 |                 | < 0.001|
## |-  Mean (SD)   | 12.977 (1.568)  | 12.742 (1.430)  | 12.860 (1.506)  |        |
## |-  Range       | 10.000 - 21.200 | 9.800 - 23.000  | 9.800 - 23.000  |        |
## |Reykingar      |                 |                 |                 | < 0.001|
## |-  No          |   782 (49.4%)   |   864 (55.5%)   |  1646 (52.4%)   |        |
## |-  Yes         |   801 (50.6%)   |   693 (44.5%)   |  1494 (47.6%)   |        |
## |Hornhimnubogi  |                 |                 |                 |   0.010|
## |-  Mean (SD)   |  0.320 (0.466)  |  0.277 (0.448)  |  0.299 (0.458)  |        |
## |-  Range       |  0.000 - 1.000  |  0.000 - 1.000  |  0.000 - 1.000  |        |
\end{verbatim}

\hypertarget{veldisvuxedsisfalliuxf0}{%
\section{Veldisvísisfallið}\label{veldisvuxedsisfalliuxf0}}

Ef við gerum ráð fyrir veldisvísivexti þá er hægt að meta t.d. 5 ára áhættu fyrir hvorn hóp. Athugið að hér erum við að gera ráð fyrir að áhættan í sérhverjum hópi haldist óbreytt út tímabilið.

Við notum formúluna \(1-e^{-\lambda*ár}\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ar <{-}}\StringTok{ }\DecValTok{5} \CommentTok{\# Hægt að velja hvaða árafjölda sem er, svo lengi sem hann er innan tímalengdar rannsóknar}
\NormalTok{VL\_}\DecValTok{0}\NormalTok{\_ahaetta <{-}}\StringTok{ }\DecValTok{1}\OperatorTok{{-}}\KeywordTok{exp}\NormalTok{(}\OperatorTok{{-}}\NormalTok{lambda\_}\DecValTok{0}\OperatorTok{*}\NormalTok{ar)}
\NormalTok{VL\_A\_ahaetta <{-}}\StringTok{ }\DecValTok{1}\OperatorTok{{-}}\KeywordTok{exp}\NormalTok{(}\OperatorTok{{-}}\NormalTok{lambda\_a}\OperatorTok{*}\NormalTok{ar)}
\NormalTok{VL\_B\_ahaetta <{-}}\StringTok{ }\DecValTok{1}\OperatorTok{{-}}\KeywordTok{exp}\NormalTok{(}\OperatorTok{{-}}\NormalTok{lambda\_b}\OperatorTok{*}\NormalTok{ar)}

\NormalTok{ar\_ahaetta <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{round}\NormalTok{(VL\_}\DecValTok{0}\NormalTok{\_ahaetta,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(VL\_A\_ahaetta,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(VL\_B\_ahaetta,}\DecValTok{4}\NormalTok{))}

\NormalTok{stats3 <{-}}\StringTok{ }\KeywordTok{as\_tibble}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(rownames,fj,st,ef,lambda\_}\DecValTok{2}\NormalTok{,ar\_ahaetta))}

\CommentTok{\# !!! ATH betra útlit}
\NormalTok{stats3 <{-}}\StringTok{ }\NormalTok{stats3 }\OperatorTok{\%>\%}\StringTok{ }\KeywordTok{rename}\NormalTok{( Hópar=}\StringTok{ }\NormalTok{rownames, Heildarfjöldi =}\StringTok{ }\NormalTok{V2,  }\DataTypeTok{Tilfelli =}\NormalTok{ V3, Eftirfylgnitími =}\StringTok{ }\NormalTok{V4, }\DataTypeTok{lambda =}\NormalTok{ V5, áhætta5ár =}\StringTok{ }\NormalTok{V6)}
\NormalTok{stats3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 6
##   Hópar Heildarfjöldi Tilfelli Eftirfylgnitími lambda áhætta5ár
##   <chr> <chr>         <chr>    <chr>           <chr>  <chr>    
## 1 Allir 3140          255      23072.54        0.0111 0.0538   
## 2 A     1583          177      11330.47        0.0156 0.0751   
## 3 B     1557          78       11742.07        0.0066 0.0327
\end{verbatim}

\hypertarget{KM}{%
\section{Kaplan Meier}\label{KM}}

\hypertarget{kaplan-meier-metilinn}{%
\subsection{Kaplan Meier metilinn}\label{kaplan-meier-metilinn}}

Næst skoðum við Kaplan Meier metilinn en hann er ein langmest notaða tölfræðiaðferðin þegar framkvæmd er lifunargreining, meðal annars vegna þess að á honum byggja svo kölluð Kaplan-Meier gröf sem eru ein algengasta leiðin til að lýsa lifunargögnum.

Fyrst skulum við kynna til sögunnar svokallað \textbf{lifunarfall} (e. survival curve). Lifunarfallið er yfirleitt táknað með \(S(t)\) og túlkun fallsins er svohljóðandi

\[ 
S(t) = \text{Líkur þess að einstaklingur fá ekki atburð fram að tíma $t$.}
\]

Lifunarfallið miðar alltaf við einhvern tiltekinn atburð. Oft er sá atburður dauði, en hann er einnig mjög oft eitthvað annað eins og til dæmis greining á sjúkdómi. Lifunarfallið gefur okkur þá líkurnar á því að hafa ekki fengið sjúkdóm innan tiltekins tíma.

Í okkar tilfelli væri \(S(5)\) líkur þess að einstaklingur fái ekki hjartasjúkdóm innan 5 ára. Ef ekki væri fyrir skerðingu væri lítill vandi að meta hvert það gildi væri, sem við samkvæmt venju köllum \(\hat S(5)\). Besta matið á \(\hat S(5)\) væri einfaldlega fjöldi þeirra sem fengu hjartasjúkdóm innan 5 ára af allri heildinni. En skerðingarinnar vegna vandast málin.

Kaplan Meier metilinn er stærðfræðileg regla til að meta \(\hat S(t)\). Hann er metinn á sérhverjum tímapunkti þegar \emph{atburður} á sér stað (en ekki skerðing). Í gögnunum okkar fengu 257 karlmenn hjartasjúkdóm svo þessir tímapunktar eru að hámarki 257. Við nánari athugun reynast stundum fleiri en einn karlmaður fá hjartasjúkdóm eftir jafnlangan tíma svo tímapunktarnir eru alls 248. Ef við gefum þeim heiti eftir stærðarröð þeirra, \(t_1, \ldots , t_{248}\), þá væri:

\begin{itemize}
\tightlist
\item
  \(t_1 =\) 18, sem er sá tímapunktur þegar fyrsti maðurinn fékk hjartasjúkdóm,
\item
  \(t_2 =\) 21 væri sá tímapunktur þegar næsti maður fékk hjartasjúkdóm
\item
  \(t_{248} =\) 3229, væri að lokum sá tímapunktur þegar síðasti maðurinn fékk hjartasjúkdóm.
\end{itemize}

Kaplan Meier metilinn er metinn á sérhverjum þessara 248 tímapunkta. Formúla metilsins er

\[ \hat S(t) = \Pi_{i=1}^k \left( 1- \frac{d_i}{n_i} \right)\]

þar sem \(d_i\) táknar fjölda þeirra sem fengu atburðinn á tímapunkti \(i\) en \(n_i\) er fjöldi þeirra sem er \emph{enn í áhættu} að fá atburðinn á tímapunkti \(i\), þ.e.a.s. hafa hvorki fengið atburðinn, né verið skertir.

Í fyrsta tímapunktinum er Kaplan Meier metillinn hreinlega hlutfall þeirra sem ekki var kominn með hjartasjúkdóm af þeim sem ekki voru orðnir skertir á þeim tímapunkti (þ.e.a.s. af þeim sem voru enn í eftirfylgd). Fyrir næsta tímapunkt þarf að reikna einn mínus hlutfall fjölda þeirra sem fékk hjartasjúkdóm \emph{á þeim tímapunkti} af þeim sem enn voru í eftirfylgd á þeim tímapunkti og margfalda það gildi við síðasta reiknaða Kaplan-Meier gildið. Þannig er haldið áfram koll af kolli fyrir alla tímapunktana. Athugið að Kaplan Meier matið er eingöngu metið á þeim tímapunktum þegar atburður á sér stað. Ef við viljum meta lifunarfallið á tímapunktum sem lenda á milli þessara gilda notum við Kaplan-Meier matið fyrir \emph{næsta tímapunkt á undan}.

Notum aðferð Kaplan Meier til að meta 5 ára áhættu á hjartasjúkdómi hjá öllum annars vegar og hópunum tveimur hins vegar. Notum fallið \(survfit\) úr pakkanum \(survival\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Allur hópurinn}
\NormalTok{KM\_}\DecValTok{0}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time\_y, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\DecValTok{1}\NormalTok{, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\NormalTok{KM\_}\DecValTok{0}\NormalTok{\_sum\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{summary}\NormalTok{(KM\_}\DecValTok{0}\NormalTok{, }\DataTypeTok{times =} \DecValTok{1}\NormalTok{) }\CommentTok{\# times = 1 fyrir 1 ár}
\NormalTok{KM\_}\DecValTok{0}\NormalTok{\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\DecValTok{1} \OperatorTok{{-}}\StringTok{ }\NormalTok{KM\_}\DecValTok{0}\NormalTok{\_sum\_}\DecValTok{1}\OperatorTok{$}\NormalTok{surv}
\NormalTok{KM\_}\DecValTok{0}\NormalTok{\_sum\_}\DecValTok{5}\NormalTok{ <{-}}\StringTok{  }\KeywordTok{summary}\NormalTok{(KM\_}\DecValTok{0}\NormalTok{, }\DataTypeTok{times =} \DecValTok{5}\NormalTok{) }\CommentTok{\# times = 5 fyrir 5 ár}
\NormalTok{KM\_}\DecValTok{0}\NormalTok{\_}\DecValTok{5}\NormalTok{ <{-}}\StringTok{ }\DecValTok{1} \OperatorTok{{-}}\StringTok{ }\NormalTok{KM\_}\DecValTok{0}\NormalTok{\_sum\_}\DecValTok{5}\OperatorTok{$}\NormalTok{surv}

\CommentTok{\# Persónuleikagerð A og B}
\NormalTok{KM\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time\_y, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{dibpat, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_sum\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{summary}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{, }\DataTypeTok{times =} \DecValTok{1}\NormalTok{) }\CommentTok{\# times = 1 fyrir 1 ár}
\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\DecValTok{1} \OperatorTok{{-}}\StringTok{ }\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_sum\_}\DecValTok{1}\OperatorTok{$}\NormalTok{surv}
\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_sum\_}\DecValTok{5}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{summary}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{, }\DataTypeTok{times =} \DecValTok{5}\NormalTok{) }\CommentTok{\# times = 5 fyrir 5 ár}
\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_}\DecValTok{5}\NormalTok{ <{-}}\StringTok{ }\DecValTok{1} \OperatorTok{{-}}\StringTok{ }\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_sum\_}\DecValTok{5}\OperatorTok{$}\NormalTok{surv}

\NormalTok{ahaetta\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{round}\NormalTok{(KM\_}\DecValTok{0}\NormalTok{\_}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_}\DecValTok{1}\NormalTok{[}\DecValTok{1}\NormalTok{] ,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_}\DecValTok{1}\NormalTok{[}\DecValTok{2}\NormalTok{], }\DecValTok{4}\NormalTok{))}
\NormalTok{ahaetta\_}\DecValTok{5}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{round}\NormalTok{(KM\_}\DecValTok{0}\NormalTok{\_}\DecValTok{5}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_}\DecValTok{5}\NormalTok{[}\DecValTok{1}\NormalTok{] ,}\DecValTok{4}\NormalTok{), }\KeywordTok{round}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_}\DecValTok{5}\NormalTok{[}\DecValTok{2}\NormalTok{], }\DecValTok{4}\NormalTok{))}

\CommentTok{\# Setjum upp í töflu og berum saman við fyrri niðurstöður.}
\NormalTok{stats4 <{-}}\StringTok{ }\KeywordTok{as\_tibble}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(rownames,lambda\_}\DecValTok{2}\NormalTok{,ar\_ahaetta, ahaetta\_}\DecValTok{1}\NormalTok{, ahaetta\_}\DecValTok{5}\NormalTok{))}

\CommentTok{\# !!! ATH betra útlit}
\CommentTok{\#stats4 <{-} stats4 \%>\% rename( Hópar= rownames, Heildarfjöldi = V2,  Tilfelli = V3, Eftirfylgnitími = V4, lambda = V5, áhætta5ár = V6)}
\NormalTok{stats4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 5
##   rownames V2     V3     V4     V5    
##   <chr>    <chr>  <chr>  <chr>  <chr> 
## 1 Allir    0.0111 0.0538 0.0048 0.0455
## 2 A        0.0156 0.0751 0.0082 0.0656
## 3 B        0.0066 0.0327 0.0013 0.0253
\end{verbatim}

Getum líka hugsað þetta út frá lifun, ef við skoðun KM\_1\_sum\_5 þá sést að 5 ára lifun fyrir A hópinn er 0.9344 og öryggisbilið er (0.9221,0.947) og 5 ára lifun fyrir B hópinn er 0.9747 og öryggisbilið er (0.9668,0.9827).

!!! ATH mjög ólíkar tölur milli veldisvísisfallsins og KM, hvernig er best að skýra það?

\hypertarget{kaplan-meier-gruxf6f}{%
\subsection{Kaplan Meier gröf}\label{kaplan-meier-gruxf6f}}

Kaplan Meier gröf eru langalgengasta myndræna framsetningin á lifunargögnum. Þau eru leið til að lýsa lifunarfallinu myndrænt, þ.e.a.s. hversu hátt hlutfall þátttakanda hefur ekki fengið atburð eftir því sem tíminn líður. Gröfin teikna Kaplan Meier matið í sérhverjum tímapunkti og flatar línur milli punktanna. Gröfin eru látin ``falla'' á þeim tímapunktum sem atburðir eiga sér stað í samræmi við það hvernig matið er reiknað. Til þessa að teikna lifunarföllin þá notum við fallið \(ggsurvplot\) úr \(survminer\).

Skoðum fyrst Kaplan-Meier graf fyrir fyrstu 100 dagana fyrir allan hópinn og notum því tímaeininguna dagur.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{KM\_}\DecValTok{0}\NormalTok{\_day <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169,chd69)}\OperatorTok{\textasciitilde{}}\DecValTok{1}\NormalTok{,}\DataTypeTok{data=}\NormalTok{wcgs)}
\NormalTok{km.plot <{-}}\StringTok{ }\KeywordTok{ggsurvplot}\NormalTok{(KM\_}\DecValTok{0}\NormalTok{\_day,}\DataTypeTok{risk.table =}\NormalTok{ T,}\DataTypeTok{break.time.by=}\DecValTok{10}\NormalTok{,}\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{110}\NormalTok{),}
                      \DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.99}\NormalTok{,}\DecValTok{1}\NormalTok{)) }
\NormalTok{km.plot }
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-21-1.pdf}

Grafið byrjar í \(y=1.00\), þegar \(t=0\), enda hefur enginn fengið hjartasjúkdóm við byrjun rannsóknarinnar. Á tíma \(t=18\) fékk fyrsti maðurinn hjartasjúkdóm. Þar dettur línan úr 1.00 í 0.9997. Næsta ``fall'' verður við \(t=21\) þegar næsti maður fékk hjartaáfall og svo koll af kolli.

Stækkum nú tímarammann okkar og skoðum Kaplan-Meier grafið fyrir fyrstu 365 dagana:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{km.plot <{-}}\StringTok{ }\KeywordTok{ggsurvplot}\NormalTok{(KM\_}\DecValTok{0}\NormalTok{\_day,}\DataTypeTok{risk.table =}\NormalTok{ T,}\DataTypeTok{break.time.by=}\DecValTok{30}\NormalTok{,}\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{365}\NormalTok{),}
                      \DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.99}\NormalTok{,}\DecValTok{1}\NormalTok{)) }
\NormalTok{km.plot }
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-22-1.pdf}

Núna hafa nokkur lóðrétt strik bæst við. Þar eiga skerðingar sér stað þ.e. á þeim tímapunktum hefur einhver þátttakandi hætt í eftirfylgd af einhverjum ástæðum. Kaplan-Meier metilinn er bara metinn á þeim tímapunktum sem atburðir eiga sér stað, svo grafið breytist ekki á þeim tímapunktum sem skerðingar eiga sér stað. Sum tímarit kjósa að fá Kaplan-Meier gröf með slíkum merkingum þegar skerðingar eru en önnur ekki. Það er ætíð hægt að stilla til í R (nota censor = FALSE í ggsurvplot).

Skoðun nú Kaplan Meier gröfin eftir persónuleikagerð. Breytum skalanum aftur í ár.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{km.plot <{-}}\StringTok{ }\KeywordTok{ggsurvplot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{,}\DataTypeTok{risk.table =}\NormalTok{ T,}
                        \DataTypeTok{break.time.by=}\DecValTok{1}\NormalTok{,}\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.8}\NormalTok{,}\DecValTok{1}\NormalTok{),}\DataTypeTok{tables.height=}\FloatTok{0.3}\NormalTok{) }
\NormalTok{km.plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-23-1.pdf}

Á þessari mynd virðist vera mikill munur á tíðni hjartasjúkdóma eftir persónuleikagerð. Rauði ferillinn, sem táknar persónuleikagerð A, er allur fyrir neðan bláa ferilinn sem táknar persónuleikagerð B. Þar af leiðandi metum við að lifunarfallið sé lægra, þ.e. að líkur þess að vera \textbf{án} hjartasjúkdóms eru minni, sem þýðir að líkurnar á því að \textbf{fá} hjartasjúkdóm eru hærri.

\hypertarget{log-rank-pruxf3f}{%
\subsection{Log-rank próf}\label{log-rank-pruxf3f}}

Nú skoðum við hvort sá munur á tíðni hjartasjúkdóma eftir persónuleikagerðunum sem við sáum bæði með Kaplan Meier metlinum og í Kaplan Meier grafinu sé tölfræðilega marktækur en allt bendir til þess að svo sé. Ein leið til að prófa þann mun er með \textbf{log-rank prófi} en það prófar hvort munur sé á tveimur lifunarföllum. Skipunin sem við notum er \(survdiff\) og er úr \(survival\) pakkanum.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{survdiff}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time\_y, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{dibpat, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## survdiff(formula = Surv(surv_time_y, status) ~ dibpat, data = wcgs_dat)
## 
##             N Observed Expected (O-E)^2/E (O-E)^2/V
## dibpat=A 1583      177      125      21.3      41.9
## dibpat=B 1557       78      130      20.6      41.9
## 
##  Chisq= 41.9  on 1 degrees of freedom, p= 9e-11
\end{verbatim}

Munurinn reyndist marktækur, p-gildið er \(1 \cdot 10^{-10}\). Logrank prófið er líka hægt að nota þegar hóparnir eru fleiri en tveir og prófa það þá núlltilgátuna hvort allir ferlarnir séu eins.

Núlltilgátan er að atburðir séu jafn tíðir milli hópanna. Taflan sýnir \emph{Expected} eða væntanlegan fjölda miðað við þá tilgátu. En gögnin sýna (\emph{Observed}) að atburðir eru færri í B hóp og fleiri í A hóp en búast mætti við ef tilgátan væri sönn. Við höfnum þeirri tilgátu og drögum þá ályktun að tíðni atburða sé meiri í A hóp.

\hypertarget{prof_haz}{%
\section{Hlutfallsleg áhætta}\label{prof_haz}}

Log-rank prófið segir okkur bara að munur sé á lifun milli hópa en ekki hve mikill hann er. Í log-rank prófinu er hægt að leiðrétta með því að gera stratified próf en það er ekki hægt að leiðrétta fyrir samfelldum breytum. Það er aftur á móti hægt í Cox líkaninu sem er aðhvarfsgreiningarlíkan. Við viljum færa okkur yfir í afhvarfsgreiningu til að meta áhrifsstærðir og til að geta leiðrétt fyrir skýribreytum (e. explanatory variables).

Cox líkanið felur í sér hlutfallslega áhættu á tímabili sem er til skoðunar.\\
Látum \(h_0(t)\) vera hættufall viðmiðunarhóps og \(h_1(t)\) vera hættufall meðferðarhóps. Ef áhættuhlutfallið er hlutfallslega jafnt gildir

\[
h_1(t) = \exp(\beta)h_0(t).
\]

Þá gildir líka með því að heilda báðum megin að
\[
H_1(t) = \exp(\beta)H_0(t).
\]

Hér er \(H_i(t)\) uppsafnaða hættufallið þ.e. \(H(t) = \int_0^t h_i(u)du\),

Notum svo logra báðum megin. Þá fæst

\[
\log(H_1(t)) = \beta + \log(H_0(t)).
\]
Með öðrum orðum: ef hlutfallsleg áhætta gildir er mismunur í logranum af uppsafnaða hættufallinu fasti á milli hópa. Fastinn er logrinn af hættuhlutfallinu.

Mynd af \(\log(H_i(t))\) á móti \(t\) gefur þá hugmynd um hvor hlutfallslega áhætta sé gild forsenda. Reyndar er betra að teikna á móti \(\log(t)\) til að teygja á tímaásnum. Það gefur skýrari mynd. Svo má rifja upp að uppsafnaða hættufallið er sama og logrinn af lifunarfallinu með neikvæðu formerki þ.e.

\[
H_i(t) = -\log(S_i(t)).
\]
Þá má skrifa:

\[
\log(-\log(S_1(t))) = \beta + \log(-\log(S_0(t))).
\]
Þess vegna er mjög algengt að skoða þessa ákveðnu vörpun af lifunarfallinu þ.e. \(y \to log(-log(y))\). Hún hefur sérstakt nafn í R og kallast \emph{cloglog} fyrir \emph{complementary log-log transformation}. Í \(survival\) pakkanum er hægt að meta lifunarföllin með aðferð Kaplan Meier og bera þau svo saman með \emph{cloglog} vörpum sem er þá samanburður á logranum af uppsafnaða hættufallinu. Fast bil ætti að vera á milli þeirra eins og kom fram að ofan. Þegar þessi vörpun er valin gildir sjálfkrafa að tímaásinn er á logra skala.

Nú skoðum við gögnin okkar henti fyrir Cox-líkan óbreytt eða hvort við þurfum að leiðrétta fyrir því að hlutfallslega áhætta gildir ekki. Skoðum gögnin í dögum.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_day <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{dibpat, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\end{Highlighting}
\end{Shaded}

Teiknum fyrst lifunargröfin:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_day,}\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.8}\NormalTok{,}\DecValTok{1}\NormalTok{),}\DataTypeTok{col =} \DecValTok{2}\OperatorTok{:}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-26-1.pdf}

Teiknum næst áhættuna \(F_i(t)=1-S_i(t)\). Það er gert með valinu \emph{fun=``event''} til að nota vörpunina \(y \to 1-y\) á lifunarfallið.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_day,}\DataTypeTok{fun=}\StringTok{"event"}\NormalTok{,}\DataTypeTok{col =} \DecValTok{2}\OperatorTok{:}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-27-1.pdf}

Biðjum næst um uppsöfnuðu hættuföllin og notum þá vörpunina \(y \to -log(y)\) á lifunarföllin því \(H_i(t) = -\log(S_i(t))\). Þetta er svo algengt að sú vörpun fær nafnið \emph{cumhaz} í lifunar pakkanum.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_day,}\DataTypeTok{fun=}\StringTok{"cumhaz"}\NormalTok{,}\DataTypeTok{col=}\DecValTok{2}\OperatorTok{:}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-28-1.pdf}

Takið eftir að hér er ekki mikill munur á \(1-S_i(t)\) og \(-log(S_i(t))\) vegna þess að

\[
-log(S_i(t))=-\log(1-(1-S_i(t))) \approx 1-S_i(t)
\]
ef \(1-S_i(t)\) er nálægt því að vera 0 þ.e. ef \(S_i(t)\) er nálægt því að vera 1.

Dæmi: Ef \(S(t)=0.85\) er \(1-S(t)=0.15\) og \(-\log(0.85)=0.16\). Þetta byggir á Taylor nálgun þar sem \(log(1-x) \approx -x\) fyrir \(x\) nálægt 0.

Að lokum veljum við \emph{cloglog} vörpunina sem við höfum mestan áhuga á ef við viljum meta hvort hlutfallsleg áhætta gildir.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_day,}\DataTypeTok{fun=}\StringTok{"cloglog"}\NormalTok{,}\DataTypeTok{col=}\DecValTok{2}\OperatorTok{:}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-29-1.pdf}
Þetta er líka hægt að gera í \(survminer\) pakkanum:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggsurvplot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_day,}\DataTypeTok{fun=}\StringTok{"cloglog"}\NormalTok{,}\DataTypeTok{risk.table =}\NormalTok{ T,}\DataTypeTok{tables.height =} \FloatTok{0.3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-30-1.pdf}
Það eru fáir atburðir fyrstu 300 dagana. En eftir það virðist fast bil vera á milli lograna af uppsöfnuðu hættuföllunum. En þau færast samt nær. Það er ekki alveg fullkomlega fast hættuhlutfall, en nógu nálægt því til þess að gera ráð fyrir að hlutfallslega áhætta gildir og beita Cox-líkaninu á óbreytt gögnin.

Skoðum einnig \emph{BMI} eftir að það er búið að skipta henni í þriðjunga og gera hana að flokkaðri skýribreytu:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{KM\_}\DecValTok{1}\NormalTok{\_bmi <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{bmiq3, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\end{Highlighting}
\end{Shaded}

Skoðum áhættuföllin:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_bmi ,}\DataTypeTok{fun =} \StringTok{"event"}\NormalTok{,}\DataTypeTok{col=}\DecValTok{2}\OperatorTok{:}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-32-1.pdf}

Svp látum við duga að skoða \emph{cloglog} grafið:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggsurvplot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_bmi ,}\DataTypeTok{fun=}\StringTok{"cloglog"}\NormalTok{,}\DataTypeTok{risk.table =}\NormalTok{ T,}\DataTypeTok{tables.height =} \FloatTok{0.35}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.
\end{verbatim}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-33-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(KM\_}\DecValTok{1}\NormalTok{\_bmi,}\DataTypeTok{fun=}\StringTok{"cloglog"}\NormalTok{,}\DataTypeTok{col=}\DecValTok{2}\OperatorTok{:}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-34-1.pdf}

Gröfin eru nokkuð samsíða eftir tímann 900. Það hafa mjög fáir atburðir gerst fyrir þann tíma. Svo hlutfallslega áhætta virðist líka gilda fyrir BMI.

\hypertarget{cox}{%
\section{Cox líkanið}\label{cox}}

Cox kom með ákveðna aðferð til að smíða likelihood fall fyrir lifunargreiningu, sjá:

Cox, David R (1972). ``Regression Models and Life-Tables''. Journal of the Royal Statistical Society, Series B. 34 (2): 187--220.

Aðferðin fellst í því að nota líkan fyrir hættufallið \(h(t)\) út frá skýribreytum þannig að grunn-hættufallið (basline hazard) er margfaldað með línulegri samantekt af skýribreytum með veldis-tengifalli.

\[
h(t) = h_0(t) \exp(\beta_1 x_1 + \cdots + \beta_p x_p),
\]
Athugið að þegar allar skýribreytur eru með gildið 0 þá er \(h(t) = h_0(t)\). M.ö.o. grunn-hættufallið fæst með því að stilla allar skýribreytur á 0 (Því er oft gott að draga meðaltalið frá gildunum eins og við gerðum fyrir aldur).

Takið svo eftir að logrinn af hættuhlutfallinu er línuleg samantekt af skýribreytum.

\[
\log \left( \frac{h(t)}{h_0(t)} \right) = \beta_1 x_1 + \cdots + \beta_j x_j + \cdots + \beta_p x_p.
\]

Hækkum nú \(x_j\) um eina einingu og skrifum

\[
\log \left( \frac{h'(t)}{h_0(t)} \right) = \beta_1 x_1 + \cdots + \beta_j ( x_j+1) + \cdots + \beta_p x_p.
\]
þar sem \(h'\) táknar hér hættufallið miðað við að \(x_j\) hafi hækkað um eina einingu. Hér er \textbf{ekki} verið að diffra, heldur er komman notuð til að merkja \(h\).

Drögum svo vinstri hliðar og hægri hliðar að ofan frá jöfnunni sem við vorum að skrifa. Þá fæst

\[
\log \left( \frac{h'(t)}{h(t)} \right) = \beta_j.
\]

Hættuhlutfallið þegar \(x_j\) hækkar um eina einingu er þar með \(e^{\beta_j}\) eða \(\exp(\beta_j)\). Hefðum við hækkað \(x_j\) um \(\Delta\) einingar væri hættuhlutfallið \(\exp(\Delta \beta_j)\).

Takið eftir hvernig \(h_0\) styttist út í svona útreikningum. Hér notum við að \(\log(u) - \log(v) = \log(\frac{u}{v})\) og að

\[
\log(a/c) - \log(b/c) = \log \left(\frac{a}{c} \cdot  \frac{c}{b} \right) = \log \left(\frac{a}{b} \right).  
\]

Cox notar svo skilyrt líkindi \(P(A|B) = P(A \cap B) / P(B)\) til að búa til hálíknafallið og nýtir sér að \(h_0\) styttist út. Við leitum svo með tölulegum aðferðum af því gildi á \(\boldsymbol{\beta}\) sem hámarkar það fall. Það er ekkert sem segir að \(\boldsymbol{\beta}\) þurfi að vera eins yfir allan tímaskalann.

Cox líkanið er í raun \emph{relative risk model} og það eru óþarfa hömlur að hugsa um Cox líkanið sem proportional hazards líkan. Það má auðveldlega leyfa áhrifum skýribreytna að breytast í tíma sem og gildunum á þeim.

Við byrjum á því að gera Cox-líkanið fyrir persónuleikagerðirnar án nokkurra frekari skýribreytna. Notum daga sem tímaeiningu.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Cox\_}\DecValTok{1}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{coxph}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{dibpat, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\end{Highlighting}
\end{Shaded}

!!! ATH, hvernær notum við ties = ``breslow''?

Prófum hvort hlutfallsleg áhætta gildir með því að meta leitnina í hættuhlutfallinu yfir tíma. Ef hlutfallslega áhætta gildir þá ætti beta(t) fallið að vera lárétt lína.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Cox\_}\FloatTok{1.}\NormalTok{zph <{-}}\StringTok{ }\KeywordTok{cox.zph}\NormalTok{(Cox\_}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(Cox\_}\FloatTok{1.}\NormalTok{zph)}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{h=}\KeywordTok{coef}\NormalTok{(Cox\_}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-37-1.pdf}
Leitnin er niður á við þ.e. hættuhlutfallið minnkar með tímanum. Lækkunin er þó ekki marktæk tölfræðilega. Sem staðfestir að okkur er óhætt að nota Cox-líkanið.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Cox\_}\FloatTok{1.}\NormalTok{zph}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        chisq df    p
## dibpat   2.6  1 0.11
## GLOBAL   2.6  1 0.11
\end{verbatim}

!!! ATH, setja frekari útskýringar varðandi myndina og töfluna fyrir ofan.\\
!!! ATH, þetta er í raun sama myndin en með transform = ``rank'', hvaða áhrif hefur það?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{czp\_}\DecValTok{2}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{cox.zph}\NormalTok{(Cox\_}\DecValTok{1}\NormalTok{,}\DataTypeTok{transform =} \StringTok{"rank"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(czp\_}\DecValTok{2}\NormalTok{)}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{h=}\KeywordTok{coef}\NormalTok{(Cox\_}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-39-1.pdf}

Skoðum nú niðurstöðu Cox-líkansins fyrir áhættuhlutfallið og berum saman við fyrri niðurstöður. Samkvæmt Cox er áhættuhlutfallið 0.43 og öryggisbilið ( 0.33, 0.56). Við fengum sama áhættuhlutfall með handreikningi og með því að gera ráð fyrir veldisvísidreifingu. !!! ATH er það rétt skilið hjá mér að það sé ekki rétt að reikna áhættuhlutfall fyrir Kaplan Meier metilinn?

Skoðum núna Cox-líkanið fyrir BMI, getum hérna notað upphaflegu samfelldu breytuna.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Cox\_}\DecValTok{2}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{coxph}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time, status) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{bmi, }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\NormalTok{Cox\_}\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## coxph(formula = Surv(surv_time, status) ~ bmi, data = wcgs_dat)
## 
##        coef exp(coef) se(coef)     z        p
## bmi 0.08863   1.09268  0.02294 3.863 0.000112
## 
## Likelihood ratio test=14.1  on 1 df, p=0.0001731
## n= 3140, number of events= 255
\end{verbatim}

Prófum hvort hlutfallleg áhætta gildir með því að meta leitnina í hættuhlutfallinu yfir tíma.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Cox\_}\FloatTok{2.}\NormalTok{zph <{-}}\StringTok{ }\KeywordTok{cox.zph}\NormalTok{(Cox\_}\DecValTok{2}\NormalTok{)}
\NormalTok{Cox\_}\FloatTok{2.}\NormalTok{zph}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           chisq df p
## bmi    4.17e-06  1 1
## GLOBAL 4.17e-06  1 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(Cox\_}\FloatTok{2.}\NormalTok{zph)}
\end{Highlighting}
\end{Shaded}

\includegraphics{BOK_files/figure-latex/unnamed-chunk-42-1.pdf}

Niðurstaðan er að hlutfallsleg áhætta virðist einnig halda fyrir bmi.

Reyndar er niðurstaðan sú sama fyrir allar helstu breytur í þessu gagnasafni. Sjáum það þegar við gerum Cox-aðhvarfslíkanið með mörgum skýribreytum.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Cox\_}\DecValTok{3}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{coxph}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(surv\_time, status) }\OperatorTok{\textasciitilde{}}\StringTok{  }\NormalTok{agec }\OperatorTok{+}\StringTok{ }\NormalTok{cholmmol }\OperatorTok{+}\StringTok{ }\NormalTok{sbp10 }\OperatorTok{+}\NormalTok{smoker }\OperatorTok{+}\StringTok{ }\NormalTok{bmi  }\OperatorTok{+}\StringTok{ }\NormalTok{dibpat }\OperatorTok{+}\StringTok{ }\NormalTok{arcus0  , }\DataTypeTok{data =}\NormalTok{ wcgs\_dat)}
\NormalTok{Cox\_}\DecValTok{3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## coxph(formula = Surv(surv_time, status) ~ agec + cholmmol + sbp10 + 
##     smoker + bmi + dibpat + arcus0, data = wcgs_dat)
## 
##               coef exp(coef) se(coef)      z        p
## agec       0.05719   1.05886  0.01135  5.040 4.64e-07
## cholmmol   0.32339   1.38181  0.04137  7.817 5.39e-15
## sbp10      0.18436   1.20245  0.03802  4.849 1.24e-06
## smokerYes  0.61075   1.84182  0.13192  4.630 3.66e-06
## bmi        0.05681   1.05846  0.02443  2.325   0.0201
## dibpatB   -0.66644   0.51353  0.13711 -4.861 1.17e-06
## arcus0     0.21561   1.24061  0.13223  1.631   0.1030
## 
## Likelihood ratio test=198.4  on 7 df, p=< 2.2e-16
## n= 3140, number of events= 255
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cox.zph}\NormalTok{(Cox\_}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           chisq df    p
## agec     1.4371  1 0.23
## cholmmol 0.3531  1 0.55
## sbp10    0.0032  1 0.95
## smoker   0.7884  1 0.37
## bmi      0.0692  1 0.79
## dibpat   2.1032  1 0.15
## arcus0   0.5778  1 0.45
## GLOBAL   5.7704  7 0.57
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cox\_}\DecValTok{3}\NormalTok{\_coef <{-}}\StringTok{ }\NormalTok{Cox\_}\DecValTok{3}\OperatorTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

Öll p-gildin eru vel yfir 0.05 sem bendir til þess að hlutfallsleg áhætta gildir fyrir allar þessar breytur.

Lifunarlíkanið sem við fáum ef við notum allar þessar breytur er \(h_{1}(t)=e^{0.0572*agec+0.3234*cholmmol+0.1844*sbp10+0.6108*smoke+0.0568*bmi+-0.6664*dibpat +0.2156*arcus}*h_{0}(t)\) Þar sem \(h_{0}(t)\) er hazard-fallið þegar allar samfelldu breyturnar eru 0, sem þýðir að upphaflega aldursbreytan er 46, reykingar og arcus eru nei og hegðunarhópurinn er B.

Þegar líkönin eru borin saman sést að stuðullinn fyrir bmi í óleiðrétta líkaninu er 0.0886 og í því leiðrétta 0.0568. !!! ATH segja eitthvað meira um túlkun á þessu.

  \bibliography{book.bib,packages.bib}

\end{document}
