<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Lifunargreining | Tölfræði fyrir almenning</title>
  <meta name="description" content="Drög að efni fyrir vefinn" />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Lifunargreining | Tölfræði fyrir almenning" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Drög að efni fyrir vefinn" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Lifunargreining | Tölfræði fyrir almenning" />
  
  <meta name="twitter:description" content="Drög að efni fyrir vefinn" />
  

<meta name="author" content="Sigurbjörg Anna Guðnadóttir" />


<meta name="date" content="2020-08-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="reg.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.2/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="reg.html"><a href="reg.html"><i class="fa fa-check"></i><b>1</b> Aðhvarfsgreining</a>
<ul>
<li class="chapter" data-level="1.1" data-path="reg.html"><a href="reg.html#línuleg-aðhvarfsgreining"><i class="fa fa-check"></i><b>1.1</b> Línuleg aðhvarfsgreining</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="reg.html"><a href="reg.html#lýsandi-tölfræði"><i class="fa fa-check"></i><b>1.1.1</b> Lýsandi tölfræði</a></li>
<li class="chapter" data-level="1.1.2" data-path="reg.html"><a href="reg.html#líkanagerð"><i class="fa fa-check"></i><b>1.1.2</b> Líkanagerð</a></li>
<li class="chapter" data-level="1.1.3" data-path="reg.html"><a href="reg.html#emmeans"><i class="fa fa-check"></i><b>1.1.3</b> Emmeans</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reg.html"><a href="reg.html#tvíkosta-aðhvarfsgreining"><i class="fa fa-check"></i><b>1.2</b> Tvíkosta aðhvarfsgreining</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lif.html"><a href="lif.html"><i class="fa fa-check"></i><b>2</b> Lifunargreining</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lif.html"><a href="lif.html#lif_skod"><i class="fa fa-check"></i><b>2.1</b> Skoðun lifunargagna</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lif.html"><a href="lif.html#sækjum-gögnin-og-lögum-til"><i class="fa fa-check"></i><b>2.1.1</b> Sækjum gögnin og lögum til</a></li>
<li class="chapter" data-level="2.1.2" data-path="lif.html"><a href="lif.html#tökum-létta-skoðun-á-gögnunum"><i class="fa fa-check"></i><b>2.1.2</b> Tökum létta skoðun á gögnunum</a></li>
<li class="chapter" data-level="2.1.3" data-path="lif.html"><a href="lif.html#veldisvísisfallið"><i class="fa fa-check"></i><b>2.1.3</b> Veldisvísisfallið</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="lif.html"><a href="lif.html#KM"><i class="fa fa-check"></i><b>2.2</b> Kaplan Meier</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="lif.html"><a href="lif.html#kaplan-meier-metilinn"><i class="fa fa-check"></i><b>2.2.1</b> Kaplan Meier metilinn</a></li>
<li class="chapter" data-level="2.2.2" data-path="lif.html"><a href="lif.html#kaplan-meier-gröf"><i class="fa fa-check"></i><b>2.2.2</b> Kaplan Meier gröf</a></li>
<li class="chapter" data-level="2.2.3" data-path="lif.html"><a href="lif.html#log-rank-próf"><i class="fa fa-check"></i><b>2.2.3</b> Log-rank próf</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="lif.html"><a href="lif.html#prof_haz"><i class="fa fa-check"></i><b>2.3</b> Hlutfallsleg áhætta</a></li>
<li class="chapter" data-level="2.4" data-path="lif.html"><a href="lif.html#cox"><i class="fa fa-check"></i><b>2.4</b> Cox líkanið</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tölfræði fyrir almenning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lif" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Lifunargreining</h1>
<p>Í þessum kafla munun við styðjast við Western Collaborative Group Study (WCGS) gagnasafnið sem er í epitools- pakkanum. Þetta eru gögn úr rannsókn þar sem meginmarkmið hennar var að skoða tengsl persónuleikagerðar og hjartasjúkdóma og því eru hjartasjúkdómar aðalútkomubreytan okkar. Viðfangsefnin voru 3154 karlmenn á aldrinum 39 - 59 ára, þeim var fylgt eftir í allt að 10 ár þangað til þeir fengu hjartasjúkdóm, eða létust, eða þeir urðu 70 ára eða eftirfylgni lauk af öðrum ástæðum. Viðfangsefnin komu inn í rannsóknina á árunum 1960-1961.</p>
<p>Við ætlum að skoða áhrif mismunandi persónuleikagerða A og B á hjartaáföll með og án skýribreytna. A og B flokkunin vísar í hvernig fólk meðhöndlar streitu og álag. Þeir sem eru í A hópi eru með meira keppnisskap, óþolinmóðari og árásagjarnari en þeir sem eru í hópi B. Þær skýribreytur sem við munum skoða eru aldur, magn kólesteról í blóði, blóðþrýstings, reykinga og BMI stuðull.</p>
<div id="lif_skod" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Skoðun lifunargagna</h2>
<div id="sækjum-gögnin-og-lögum-til" class="section level3" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Sækjum gögnin og lögum til</h3>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="lif.html#cb7-1"></a><span class="kw">data</span>(wcgs,<span class="dt">package =</span> <span class="st">&quot;epitools&quot;</span>)</span>
<span id="cb7-2"><a href="lif.html#cb7-2"></a>wcgs &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(wcgs)</span>
<span id="cb7-3"><a href="lif.html#cb7-3"></a></span>
<span id="cb7-4"><a href="lif.html#cb7-4"></a>wcgs &lt;-<span class="st"> </span>wcgs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb7-5"><a href="lif.html#cb7-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">surv_time_y =</span> time169 <span class="op">/</span><span class="st"> </span><span class="fl">365.24</span>,</span>
<span id="cb7-6"><a href="lif.html#cb7-6"></a>         <span class="dt">agec =</span> age0 <span class="op">-</span><span class="st"> </span><span class="dv">46</span>,</span>
<span id="cb7-7"><a href="lif.html#cb7-7"></a>         <span class="dt">cholmmol =</span> chol0 <span class="op">/</span><span class="st"> </span><span class="dv">39</span>,</span>
<span id="cb7-8"><a href="lif.html#cb7-8"></a>         <span class="dt">sbp10 =</span> sbp0 <span class="op">/</span><span class="st"> </span><span class="dv">10</span>,</span>
<span id="cb7-9"><a href="lif.html#cb7-9"></a>         <span class="dt">dibpat =</span> <span class="kw">factor</span>(dibpat0, <span class="dt">levels =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span>)),</span>
<span id="cb7-10"><a href="lif.html#cb7-10"></a>         <span class="dt">smoker =</span> <span class="kw">factor</span>(<span class="dv">1</span> <span class="op">*</span><span class="st"> </span>(ncigs0 <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>), <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)),</span>
<span id="cb7-11"><a href="lif.html#cb7-11"></a>         <span class="dt">bmi =</span> ((weight0 <span class="op">*</span><span class="st"> </span><span class="fl">2.54</span>) <span class="op">/</span><span class="st"> </span><span class="dv">100</span>) <span class="op">/</span><span class="st"> </span>(height0 <span class="op">*</span><span class="st"> </span><span class="fl">2.54</span>)<span class="op">^</span><span class="dv">2</span>,</span>
<span id="cb7-12"><a href="lif.html#cb7-12"></a>         <span class="dt">bmiq3 =</span> <span class="kw">cut</span>(bmi, <span class="dt">breaks =</span> <span class="kw">quantile</span>(bmi, <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="op">/</span><span class="dv">3</span>)),</span>
<span id="cb7-13"><a href="lif.html#cb7-13"></a>                       <span class="dt">include.lowest =</span> T, <span class="dt">right =</span> F)</span>
<span id="cb7-14"><a href="lif.html#cb7-14"></a>         )</span>
<span id="cb7-15"><a href="lif.html#cb7-15"></a>wcgs_dat &lt;-<span class="st"> </span>wcgs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb7-16"><a href="lif.html#cb7-16"></a><span class="st">  </span><span class="kw">select</span>(id, <span class="dt">surv_time =</span> time169, surv_time_y, <span class="dt">status=</span>chd69,  agec, cholmmol, sbp10, smoker, dibpat, bmi,bmiq3, arcus0) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb7-17"><a href="lif.html#cb7-17"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(.)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">statusf=</span><span class="kw">factor</span>(status,<span class="dt">levels=</span><span class="dv">0</span><span class="op">:</span><span class="dv">1</span>,<span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;No event&quot;</span>,<span class="st">&quot;Yes event&quot;</span>)))</span>
<span id="cb7-18"><a href="lif.html#cb7-18"></a></span>
<span id="cb7-19"><a href="lif.html#cb7-19"></a>wcgs_dat<span class="op">$</span>dibpat &lt;-<span class="st"> </span><span class="kw">relevel</span>(wcgs_dat<span class="op">$</span>dibpat, <span class="st">&quot;A&quot;</span>)</span></code></pre></div>
<p>Tíminn time169 er í dögum en við reiknum nýja breytu sem mælir tímann í árum.<br />
Við búum til nýja aldursbreytu þar sem við erum búin að staðla hana m.v. meðaldurinn í hópnum. Meðalaldurinn er 46.28 og drögum við þvi 46 frá aldrinum. Það mun auðvelda túlkun á líkönum.<br />
!!! ATH af hverju deilum við með 10 og 39?.<br />
Breytan dibpat0 eru persónuleikagerðirnar, við setjum hana sem flokkabreytu (e. factor).<br />
Við skilgreinum reykingamann þann sem reykir amk 1 sígaréttu á dag og höfum breytuna sem flokkabreytu.<br />
Til þess að reikna BMI þá þurfum við að breyta hæðinni í metra og þyngdinni í kíló. Útbúum einnig flokkabretytu fyrir bmi þar sem við skiptum henni í 3 jafna hluta.
Breytan chd69 segir til um hvort karlmennirnir fengu hjartasjúkdóm eða ekki og setjum við hana því sem “status”, það hvort atburður hafi átt sér stað eða ekki er oft kallað “status”.</p>
<p>Við notum bara þá einstaklinga sem hafa allar breyturnar sem við ætlum að skoða, aðra fjarlægjum við úr gagnasafninu.</p>
</div>
<div id="tökum-létta-skoðun-á-gögnunum" class="section level3" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Tökum létta skoðun á gögnunum</h3>
<p>Fyrsta skrefið er alltaf að skoða gögnin og sjá hvað einfaldur reikningur gefur okkur. Við skoðum gögnin miða við ár sem tímalengd.</p>
<p><em>Helstu tölur</em></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="lif.html#cb8-1"></a><span class="co"># Hversu margir eru í safninu og í hvorum hópi fyrir sig?</span></span>
<span id="cb8-2"><a href="lif.html#cb8-2"></a>rownames &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Allir&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>)</span>
<span id="cb8-3"><a href="lif.html#cb8-3"></a>fj_t &lt;-<span class="st"> </span><span class="kw">dim</span>(wcgs_dat)[<span class="dv">1</span>]</span>
<span id="cb8-4"><a href="lif.html#cb8-4"></a>fj_g &lt;-<span class="st"> </span>wcgs_dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb8-5"><a href="lif.html#cb8-5"></a><span class="st">  </span><span class="kw">group_by</span>(dibpat) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb8-6"><a href="lif.html#cb8-6"></a><span class="st">  </span><span class="kw">count</span>()</span>
<span id="cb8-7"><a href="lif.html#cb8-7"></a></span>
<span id="cb8-8"><a href="lif.html#cb8-8"></a>fj &lt;-<span class="st"> </span><span class="kw">rbind</span>(fj_t,fj_g[[<span class="dv">1</span>,<span class="dv">2</span>]],fj_g[[<span class="dv">2</span>,<span class="dv">2</span>]])</span>
<span id="cb8-9"><a href="lif.html#cb8-9"></a></span>
<span id="cb8-10"><a href="lif.html#cb8-10"></a><span class="co"># Hversu margir fengu hjartaáfall í heildina og í hvorum hópi fyrir sig?</span></span>
<span id="cb8-11"><a href="lif.html#cb8-11"></a></span>
<span id="cb8-12"><a href="lif.html#cb8-12"></a>st_t &lt;-<span class="st"> </span><span class="kw">sum</span>(wcgs_dat<span class="op">$</span>status)</span>
<span id="cb8-13"><a href="lif.html#cb8-13"></a>st_g &lt;-<span class="st"> </span>wcgs_dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb8-14"><a href="lif.html#cb8-14"></a><span class="st">  </span><span class="kw">group_by</span>(dibpat) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb8-15"><a href="lif.html#cb8-15"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">tidni =</span> <span class="kw">sum</span>(status))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="lif.html#cb10-1"></a>st &lt;-<span class="st"> </span><span class="kw">rbind</span>(st_t,st_g[[<span class="dv">1</span>,<span class="dv">2</span>]],st_g[[<span class="dv">2</span>,<span class="dv">2</span>]])</span>
<span id="cb10-2"><a href="lif.html#cb10-2"></a></span>
<span id="cb10-3"><a href="lif.html#cb10-3"></a><span class="co"># Hver er eftirfylgnitíminn og lambda fyrir all hópana?</span></span>
<span id="cb10-4"><a href="lif.html#cb10-4"></a></span>
<span id="cb10-5"><a href="lif.html#cb10-5"></a>ef_t &lt;-<span class="st"> </span>wcgs_dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-6"><a href="lif.html#cb10-6"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">sum_time =</span> <span class="kw">sum</span>(surv_time_y),<span class="dt">lambda =</span> <span class="kw">sum</span>(status) <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(surv_time_y))</span>
<span id="cb10-7"><a href="lif.html#cb10-7"></a></span>
<span id="cb10-8"><a href="lif.html#cb10-8"></a>ef_g &lt;-<span class="st"> </span>wcgs_lambda &lt;-<span class="st"> </span>wcgs_dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-9"><a href="lif.html#cb10-9"></a><span class="st">  </span><span class="kw">group_by</span>(dibpat) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-10"><a href="lif.html#cb10-10"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">sum_time =</span> <span class="kw">sum</span>(surv_time_y),<span class="dt">lambda =</span> <span class="kw">sum</span>(status) <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(surv_time_y))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="lif.html#cb12-1"></a>ef &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">round</span>(ef_t[[<span class="dv">1</span>]],<span class="dv">2</span>), <span class="kw">round</span>(ef_g[[<span class="dv">1</span>,<span class="dv">2</span>]],<span class="dv">2</span>), <span class="kw">round</span>(ef_g[[<span class="dv">2</span>,<span class="dv">2</span>]],<span class="dv">2</span>))</span>
<span id="cb12-2"><a href="lif.html#cb12-2"></a>lambda &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">round</span>(ef_t[[<span class="dv">2</span>]],<span class="dv">4</span>), <span class="kw">round</span>(ef_g[[<span class="dv">1</span>,<span class="dv">3</span>]],<span class="dv">4</span>), <span class="kw">round</span>(ef_g[[<span class="dv">2</span>,<span class="dv">3</span>]],<span class="dv">4</span>))</span>
<span id="cb12-3"><a href="lif.html#cb12-3"></a></span>
<span id="cb12-4"><a href="lif.html#cb12-4"></a><span class="co"># Setjum í eina töflu</span></span>
<span id="cb12-5"><a href="lif.html#cb12-5"></a>stats &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">cbind</span>(rownames,fj,st,ef,lambda))</span></code></pre></div>
<pre><code>## Warning: The `x` argument of `as_tibble.matrix()` must have column names if `.name_repair` is omitted as of tibble 2.0.0.
## Using compatibility `.name_repair`.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="lif.html#cb14-1"></a><span class="co"># !!! ATH betra útlit</span></span>
<span id="cb14-2"><a href="lif.html#cb14-2"></a>stats &lt;-stats <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rename</span>( Hópar=<span class="st"> </span>rownames, Heildarfjöldi =<span class="st"> </span>V2,  <span class="dt">Tilfelli =</span> V3, Eftirfylgnitími =<span class="st"> </span>V4, <span class="dt">lambda =</span> V5)</span>
<span id="cb14-3"><a href="lif.html#cb14-3"></a>stats</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   Hópar Heildarfjöldi Tilfelli Eftirfylgnitími lambda
##   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;    &lt;chr&gt;           &lt;chr&gt; 
## 1 Allir 3140          255      23072.54        0.0111
## 2 A     1583          177      11330.47        0.0156
## 3 B     1557          78       11742.07        0.0066</code></pre>
<p>Eftirfylgnitíminn er sá tími sem einstaklingur er í rannsókninni, hámark 10 ár í þessari rannsókn. Lambda er fjöldi atburða á tímaeiningu, í þessu tilfelli er það eitt ár. Svo 0.0111 eða 1.11 % er eins árs meðaláhætta fyrir heildarhópinn.</p>
<p><em>Áhættuhlutfallið</em>
Áhættuhlutfallið er hlutfallið af líkunum á því að atburðurinn gerist í meðferðarhópnum á móti líkunum á því að atburðurinn gerist í viðmiðunarhópnum. Við lítum á persónuleikagerð A sem meðferðarhópinn og persónuleikagerð B sem viðmiðunarhópinn.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="lif.html#cb16-1"></a>hz &lt;-<span class="st"> </span>wcgs_lambda<span class="op">$</span>lambda[<span class="dv">2</span>]<span class="op">/</span>wcgs_lambda<span class="op">$</span>lambda[<span class="dv">1</span>] </span></code></pre></div>
<p>Áhættuhlutfallið er 0.43 og því er einstaklingur með persónuleikagerð A í -57% meiri áhættu til að fá hjartaáfall ef allir aðrir þættir eru eins.</p>
<p>Af þessum gildum höfum við mestan áhuga áhættunni (þ.e. lambda) fyrir hvora persónuleikagerð fyrir sig og áhættuhlutfallinu. Fallið <span class="math inline">\(flexsurvreg\)</span> úr pakkanum <span class="math inline">\(flexsurv\)</span> hentar vel til þess að reikna það. Einnig notum við fallið <span class="math inline">\(Surv\)</span> úr pakkanum <span class="math inline">\(survival\)</span>.<br />
Fallið <span class="math inline">\(Surv\)</span> er notað til að útbúa breytu af gerðinni lifunarhlutur (e. survival object). Það tekur inn í sig tvær breytur; annars vegar hversu langur tími leið fram að atburði eða skerðingu og hins vegar hvort atburður eða skerðing átti stað á þeim tímapunkti. Þeir sem hafa ekki fengið hjartaáfall eru með skerðingu.</p>
<p>Líkanið sem við köllum VL_O er notað til að reikna lambda fyrir allan hópinn en VL_1 til þess að reikna lambda fyrir hópa A og B.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="lif.html#cb17-1"></a>VL_<span class="dv">0</span> &lt;-<span class="st"> </span><span class="kw">flexsurvreg</span>(<span class="kw">Surv</span>(surv_time_y, status) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>,<span class="dt">data=</span>wcgs_dat,<span class="dt">dist=</span><span class="st">&quot;exponential&quot;</span>)</span>
<span id="cb17-2"><a href="lif.html#cb17-2"></a>VL_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">flexsurvreg</span>(<span class="kw">Surv</span>(surv_time_y, status) <span class="op">~</span><span class="st"> </span>dibpat,<span class="dt">data=</span>wcgs_dat,<span class="dt">dist=</span><span class="st">&quot;exponential&quot;</span>)</span>
<span id="cb17-3"><a href="lif.html#cb17-3"></a></span>
<span id="cb17-4"><a href="lif.html#cb17-4"></a>lambda_<span class="dv">0</span> &lt;-<span class="st"> </span>VL_<span class="dv">0</span><span class="op">$</span>res[<span class="dv">1</span>,<span class="dv">1</span>]</span>
<span id="cb17-5"><a href="lif.html#cb17-5"></a>lambda_a &lt;-<span class="st"> </span>VL_<span class="dv">1</span><span class="op">$</span>res[<span class="dv">1</span>,<span class="dv">1</span>] </span>
<span id="cb17-6"><a href="lif.html#cb17-6"></a>lambda_b &lt;-<span class="st"> </span><span class="kw">exp</span>(VL_<span class="dv">1</span><span class="op">$</span>res[<span class="dv">2</span>,<span class="dv">1</span>]<span class="op">+</span><span class="kw">log</span>(VL_<span class="dv">1</span><span class="op">$</span>res[<span class="dv">1</span>,<span class="dv">1</span>])) </span>
<span id="cb17-7"><a href="lif.html#cb17-7"></a></span>
<span id="cb17-8"><a href="lif.html#cb17-8"></a></span>
<span id="cb17-9"><a href="lif.html#cb17-9"></a>lambda_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">round</span>(lambda_<span class="dv">0</span>,<span class="dv">4</span>), <span class="kw">round</span>(lambda_a,<span class="dv">4</span>), <span class="kw">round</span>(lambda_b,<span class="dv">4</span>))</span>
<span id="cb17-10"><a href="lif.html#cb17-10"></a></span>
<span id="cb17-11"><a href="lif.html#cb17-11"></a><span class="co"># Setjum í eina töflu</span></span>
<span id="cb17-12"><a href="lif.html#cb17-12"></a>stats2 &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">cbind</span>(rownames, lambda, lambda_<span class="dv">2</span>))</span>
<span id="cb17-13"><a href="lif.html#cb17-13"></a></span>
<span id="cb17-14"><a href="lif.html#cb17-14"></a><span class="co"># !!! ATH betra útlit</span></span>
<span id="cb17-15"><a href="lif.html#cb17-15"></a>stats2 &lt;-<span class="st"> </span>stats2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rename</span>( Hópar=<span class="st"> </span>rownames, Lambda_handreiknað =<span class="st"> </span>V2,  Lambda_með<span class="dt">_falli =</span> V3)</span>
<span id="cb17-16"><a href="lif.html#cb17-16"></a>stats2</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   Hópar Lambda_handreiknað Lambda_með_falli
##   &lt;chr&gt; &lt;chr&gt;              &lt;chr&gt;           
## 1 Allir 0.0111             0.0111          
## 2 A     0.0156             0.0156          
## 3 B     0.0066             0.0066</code></pre>
<p>Getum líka reiknað áhættuhlutfallið</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="lif.html#cb19-1"></a>hz_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">exp</span>(VL_<span class="dv">1</span><span class="op">$</span>res[<span class="dv">2</span>,<span class="dv">1</span>])</span></code></pre></div>
<p>Áhættuhlutfallið er 0.43 sem er það sama og við fengum með handreikningi.</p>
</div>
<div id="veldisvísisfallið" class="section level3" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Veldisvísisfallið</h3>
<p>Ef við gerum ráð fyrir veldisvísivexti þá er hægt að meta t.d. 5 ára áhættu fyrir hvorn hóp. Athugið að hér erum við að gera ráð fyrir að áhættan í sérhverjum hópi haldist óbreytt út tímabilið.</p>
<p>Við notum formúluna <span class="math inline">\(1-e^{-\lambda*ár}\)</span>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="lif.html#cb20-1"></a>ar &lt;-<span class="st"> </span><span class="dv">5</span> <span class="co"># Hægt að velja hvaða árafjölda sem er, svo lengi sem hann er innan tímalengdar rannsóknar</span></span>
<span id="cb20-2"><a href="lif.html#cb20-2"></a>VL_<span class="dv">0</span>_ahaetta &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">exp</span>(<span class="op">-</span>lambda_<span class="dv">0</span><span class="op">*</span>ar)</span>
<span id="cb20-3"><a href="lif.html#cb20-3"></a>VL_A_ahaetta &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">exp</span>(<span class="op">-</span>lambda_a<span class="op">*</span>ar)</span>
<span id="cb20-4"><a href="lif.html#cb20-4"></a>VL_B_ahaetta &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">exp</span>(<span class="op">-</span>lambda_b<span class="op">*</span>ar)</span>
<span id="cb20-5"><a href="lif.html#cb20-5"></a></span>
<span id="cb20-6"><a href="lif.html#cb20-6"></a>ar_ahaetta &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">round</span>(VL_<span class="dv">0</span>_ahaetta,<span class="dv">4</span>), <span class="kw">round</span>(VL_A_ahaetta,<span class="dv">4</span>), <span class="kw">round</span>(VL_B_ahaetta,<span class="dv">4</span>))</span>
<span id="cb20-7"><a href="lif.html#cb20-7"></a></span>
<span id="cb20-8"><a href="lif.html#cb20-8"></a>stats3 &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">cbind</span>(rownames,fj,st,ef,lambda_<span class="dv">2</span>,ar_ahaetta))</span>
<span id="cb20-9"><a href="lif.html#cb20-9"></a></span>
<span id="cb20-10"><a href="lif.html#cb20-10"></a><span class="co"># !!! ATH betra útlit</span></span>
<span id="cb20-11"><a href="lif.html#cb20-11"></a>stats3 &lt;-<span class="st"> </span>stats3 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rename</span>( Hópar=<span class="st"> </span>rownames, Heildarfjöldi =<span class="st"> </span>V2,  <span class="dt">Tilfelli =</span> V3, Eftirfylgnitími =<span class="st"> </span>V4, <span class="dt">lambda =</span> V5, áhætta5ár =<span class="st"> </span>V6)</span>
<span id="cb20-12"><a href="lif.html#cb20-12"></a>stats3</span></code></pre></div>
<pre><code>## # A tibble: 3 x 6
##   Hópar Heildarfjöldi Tilfelli Eftirfylgnitími lambda áhætta5ár
##   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;    &lt;chr&gt;           &lt;chr&gt;  &lt;chr&gt;    
## 1 Allir 3140          255      23072.54        0.0111 0.0538   
## 2 A     1583          177      11330.47        0.0156 0.0751   
## 3 B     1557          78       11742.07        0.0066 0.0327</code></pre>

</div>
</div>
<div id="KM" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Kaplan Meier</h2>
<div id="kaplan-meier-metilinn" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Kaplan Meier metilinn</h3>
<p>Næst skoðum við Kaplan Meier metilinn en hann er ein langmest notaða tölfræðiaðferðin þegar framkvæmd er lifunargreining, meðal annars vegna þess að á honum byggja svo kölluð Kaplan-Meier gröf sem eru ein algengasta leiðin til að lýsa lifunargögnum.</p>
<p>Fyrst skulum við kynna til sögunnar svokallað <strong>lifunarfall</strong> (e. survival curve). Lifunarfallið er yfirleitt táknað með <span class="math inline">\(S(t)\)</span> og túlkun fallsins er svohljóðandi</p>
<p><span class="math display">\[ 
S(t) = \text{Líkur þess að einstaklingur fá ekki atburð fram að tíma $t$.}
\]</span></p>
<p>Lifunarfallið miðar alltaf við einhvern tiltekinn atburð. Oft er sá atburður dauði, en hann er einnig mjög oft eitthvað annað eins og til dæmis greining á sjúkdómi. Lifunarfallið gefur okkur þá líkurnar á því að hafa ekki fengið sjúkdóm innan tiltekins tíma.</p>
<p>Í okkar tilfelli væri <span class="math inline">\(S(5)\)</span> líkur þess að einstaklingur fái ekki hjartasjúkdóm innan 5 ára. Ef ekki væri fyrir skerðingu væri lítill vandi að meta hvert það gildi væri, sem við samkvæmt venju köllum <span class="math inline">\(\hat S(5)\)</span>. Besta matið á <span class="math inline">\(\hat S(5)\)</span> væri einfaldlega fjöldi þeirra sem fengu hjartasjúkdóm innan 5 ára af allri heildinni. En skerðingarinnar vegna vandast málin.</p>
<p>Kaplan Meier metilinn er stærðfræðileg regla til að meta <span class="math inline">\(\hat S(t)\)</span>. Hann er metinn á sérhverjum tímapunkti þegar <em>atburður</em> á sér stað (en ekki skerðing). Í gögnunum okkar fengu 257 karlmenn hjartasjúkdóm svo þessir tímapunktar eru að hámarki 257. Við nánari athugun reynast stundum fleiri en einn karlmaður fá hjartasjúkdóm eftir jafnlangan tíma svo tímapunktarnir eru alls 248. Ef við gefum þeim heiti eftir stærðarröð þeirra, <span class="math inline">\(t_1, \ldots , t_{248}\)</span>, þá væri:</p>
<ul>
<li><span class="math inline">\(t_1 =\)</span> 18, sem er sá tímapunktur þegar fyrsti maðurinn fékk hjartasjúkdóm,</li>
<li><span class="math inline">\(t_2 =\)</span> 21 væri sá tímapunktur þegar næsti maður fékk hjartasjúkdóm</li>
<li><span class="math inline">\(t_{248} =\)</span> 3229, væri að lokum sá tímapunktur þegar síðasti maðurinn fékk hjartasjúkdóm.</li>
</ul>
<p>Kaplan Meier metilinn er metinn á sérhverjum þessara 248 tímapunkta. Formúla metilsins er</p>
<p><span class="math display">\[ \hat S(t) = \Pi_{i=1}^k \left( 1- \frac{d_i}{n_i} \right)\]</span></p>
<p>þar sem <span class="math inline">\(d_i\)</span> táknar fjölda þeirra sem fengu atburðinn á tímapunkti <span class="math inline">\(i\)</span> en <span class="math inline">\(n_i\)</span> er fjöldi þeirra sem er <em>enn í áhættu</em> að fá atburðinn á tímapunkti <span class="math inline">\(i\)</span>, þ.e.a.s. hafa hvorki fengið atburðinn, né verið skertir.</p>
<p>Í fyrsta tímapunktinum er Kaplan Meier metillinn hreinlega hlutfall þeirra sem ekki var kominn með hjartasjúkdóm af þeim sem ekki voru orðnir skertir á þeim tímapunkti (þ.e.a.s. af þeim sem voru enn í eftirfylgd). Fyrir næsta tímapunkt þarf að reikna einn mínus hlutfall fjölda þeirra sem fékk hjartasjúkdóm <em>á þeim tímapunkti</em> af þeim sem enn voru í eftirfylgd á þeim tímapunkti og margfalda það gildi við síðasta reiknaða Kaplan-Meier gildið. Þannig er haldið áfram koll af kolli fyrir alla tímapunktana. Athugið að Kaplan Meier matið er eingöngu metið á þeim tímapunktum þegar atburður á sér stað. Ef við viljum meta lifunarfallið á tímapunktum sem lenda á milli þessara gilda notum við Kaplan-Meier matið fyrir <em>næsta tímapunkt á undan</em>.</p>
<p>Notum aðferð Kaplan Meier til að meta 5 ára áhættu á hjartasjúkdómi hjá öllum annars vegar og hópunum tveimur hins vegar. Notum fallið <span class="math inline">\(survfit\)</span> úr pakkanum <span class="math inline">\(survival\)</span>.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="lif.html#cb22-1"></a><span class="co"># Allur hópurinn</span></span>
<span id="cb22-2"><a href="lif.html#cb22-2"></a>KM_<span class="dv">0</span> &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(surv_time_y, status) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> wcgs_dat)</span>
<span id="cb22-3"><a href="lif.html#cb22-3"></a>KM_<span class="dv">0</span>_sum_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">summary</span>(KM_<span class="dv">0</span>, <span class="dt">times =</span> <span class="dv">1</span>) <span class="co"># times = 1 fyrir 1 ár</span></span>
<span id="cb22-4"><a href="lif.html#cb22-4"></a>KM_<span class="dv">0</span>_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>KM_<span class="dv">0</span>_sum_<span class="dv">1</span><span class="op">$</span>surv</span>
<span id="cb22-5"><a href="lif.html#cb22-5"></a>KM_<span class="dv">0</span>_sum_<span class="dv">5</span> &lt;-<span class="st">  </span><span class="kw">summary</span>(KM_<span class="dv">0</span>, <span class="dt">times =</span> <span class="dv">5</span>) <span class="co"># times = 5 fyrir 5 ár</span></span>
<span id="cb22-6"><a href="lif.html#cb22-6"></a>KM_<span class="dv">0</span>_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>KM_<span class="dv">0</span>_sum_<span class="dv">5</span><span class="op">$</span>surv</span>
<span id="cb22-7"><a href="lif.html#cb22-7"></a></span>
<span id="cb22-8"><a href="lif.html#cb22-8"></a><span class="co"># Persónuleikagerð A og B</span></span>
<span id="cb22-9"><a href="lif.html#cb22-9"></a>KM_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(surv_time_y, status) <span class="op">~</span><span class="st"> </span>dibpat, <span class="dt">data =</span> wcgs_dat)</span>
<span id="cb22-10"><a href="lif.html#cb22-10"></a>KM_<span class="dv">1</span>_sum_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">summary</span>(KM_<span class="dv">1</span>, <span class="dt">times =</span> <span class="dv">1</span>) <span class="co"># times = 1 fyrir 1 ár</span></span>
<span id="cb22-11"><a href="lif.html#cb22-11"></a>KM_<span class="dv">1</span>_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>KM_<span class="dv">1</span>_sum_<span class="dv">1</span><span class="op">$</span>surv</span>
<span id="cb22-12"><a href="lif.html#cb22-12"></a>KM_<span class="dv">1</span>_sum_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">summary</span>(KM_<span class="dv">1</span>, <span class="dt">times =</span> <span class="dv">5</span>) <span class="co"># times = 5 fyrir 5 ár</span></span>
<span id="cb22-13"><a href="lif.html#cb22-13"></a>KM_<span class="dv">1</span>_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>KM_<span class="dv">1</span>_sum_<span class="dv">5</span><span class="op">$</span>surv</span>
<span id="cb22-14"><a href="lif.html#cb22-14"></a></span>
<span id="cb22-15"><a href="lif.html#cb22-15"></a>ahaetta_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">round</span>(KM_<span class="dv">0</span>_<span class="dv">1</span>,<span class="dv">4</span>), <span class="kw">round</span>(KM_<span class="dv">1</span>_<span class="dv">1</span>[<span class="dv">1</span>] ,<span class="dv">4</span>), <span class="kw">round</span>(KM_<span class="dv">1</span>_<span class="dv">1</span>[<span class="dv">2</span>], <span class="dv">4</span>))</span>
<span id="cb22-16"><a href="lif.html#cb22-16"></a>ahaetta_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">round</span>(KM_<span class="dv">0</span>_<span class="dv">5</span>,<span class="dv">4</span>), <span class="kw">round</span>(KM_<span class="dv">1</span>_<span class="dv">5</span>[<span class="dv">1</span>] ,<span class="dv">4</span>), <span class="kw">round</span>(KM_<span class="dv">1</span>_<span class="dv">5</span>[<span class="dv">2</span>], <span class="dv">4</span>))</span>
<span id="cb22-17"><a href="lif.html#cb22-17"></a></span>
<span id="cb22-18"><a href="lif.html#cb22-18"></a><span class="co"># Setjum upp í töflu og berum saman við fyrri niðurstöður.</span></span>
<span id="cb22-19"><a href="lif.html#cb22-19"></a>stats4 &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">cbind</span>(rownames,lambda_<span class="dv">2</span>,ar_ahaetta, ahaetta_<span class="dv">1</span>, ahaetta_<span class="dv">5</span>))</span>
<span id="cb22-20"><a href="lif.html#cb22-20"></a></span>
<span id="cb22-21"><a href="lif.html#cb22-21"></a><span class="co"># !!! ATH betra útlit</span></span>
<span id="cb22-22"><a href="lif.html#cb22-22"></a><span class="co">#stats4 &lt;- stats4 %&gt;% rename( Hópar= rownames, Heildarfjöldi = V2,  Tilfelli = V3, Eftirfylgnitími = V4, lambda = V5, áhætta5ár = V6)</span></span>
<span id="cb22-23"><a href="lif.html#cb22-23"></a>stats4</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   rownames V2     V3     V4     V5    
##   &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt; 
## 1 Allir    0.0111 0.0538 0.0048 0.0455
## 2 A        0.0156 0.0751 0.0082 0.0656
## 3 B        0.0066 0.0327 0.0013 0.0253</code></pre>
<p>Getum líka hugsað þetta út frá lifun, ef við skoðun KM_1_sum_5 þá sést að 5 ára lifun fyrir A hópinn er 0.9344 og öryggisbilið er (0.9221,0.947) og 5 ára lifun fyrir B hópinn er 0.9747 og öryggisbilið er (0.9668,0.9827).</p>
<p>!!! ATH mjög ólíkar tölur milli veldisvísisfallsins og KM, hvernig er best að skýra það?</p>
</div>
<div id="kaplan-meier-gröf" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Kaplan Meier gröf</h3>
<p>Kaplan Meier gröf eru langalgengasta myndræna framsetningin á lifunargögnum. Þau eru leið til að lýsa lifunarfallinu myndrænt, þ.e.a.s. hversu hátt hlutfall þátttakanda hefur ekki fengið atburð eftir því sem tíminn líður. Gröfin teikna Kaplan Meier matið í sérhverjum tímapunkti og flatar línur milli punktanna. Gröfin eru látin “falla” á þeim tímapunktum sem atburðir eiga sér stað í samræmi við það hvernig matið er reiknað. Til þessa að teikna lifunarföllin þá notum við fallið <span class="math inline">\(ggsurvplot\)</span> úr <span class="math inline">\(survminer\)</span>.</p>
<p>Skoðum fyrst Kaplan-Meier graf fyrir fyrstu 100 dagana fyrir allan hópinn og notum því tímaeininguna dagur.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="lif.html#cb24-1"></a>KM_<span class="dv">0</span>_day &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(time169,chd69)<span class="op">~</span><span class="dv">1</span>,<span class="dt">data=</span>wcgs)</span>
<span id="cb24-2"><a href="lif.html#cb24-2"></a>km.plot &lt;-<span class="st"> </span><span class="kw">ggsurvplot</span>(KM_<span class="dv">0</span>_day,<span class="dt">risk.table =</span> T,<span class="dt">break.time.by=</span><span class="dv">10</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">110</span>),</span>
<span id="cb24-3"><a href="lif.html#cb24-3"></a>                      <span class="dt">ylim=</span><span class="kw">c</span>(<span class="fl">0.99</span>,<span class="dv">1</span>)) </span>
<span id="cb24-4"><a href="lif.html#cb24-4"></a>km.plot </span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Grafið byrjar í <span class="math inline">\(y=1.00\)</span>, þegar <span class="math inline">\(t=0\)</span>, enda hefur enginn fengið hjartasjúkdóm við byrjun rannsóknarinnar. Á tíma <span class="math inline">\(t=18\)</span> fékk fyrsti maðurinn hjartasjúkdóm. Þar dettur línan úr 1.00 í 0.9997. Næsta “fall” verður við <span class="math inline">\(t=21\)</span> þegar næsti maður fékk hjartaáfall og svo koll af kolli.</p>
<p>Stækkum nú tímarammann okkar og skoðum Kaplan-Meier grafið fyrir fyrstu 365 dagana:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="lif.html#cb25-1"></a>km.plot &lt;-<span class="st"> </span><span class="kw">ggsurvplot</span>(KM_<span class="dv">0</span>_day,<span class="dt">risk.table =</span> T,<span class="dt">break.time.by=</span><span class="dv">30</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">365</span>),</span>
<span id="cb25-2"><a href="lif.html#cb25-2"></a>                      <span class="dt">ylim=</span><span class="kw">c</span>(<span class="fl">0.99</span>,<span class="dv">1</span>)) </span>
<span id="cb25-3"><a href="lif.html#cb25-3"></a>km.plot </span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Núna hafa nokkur lóðrétt strik bæst við. Þar eiga skerðingar sér stað þ.e. á þeim tímapunktum hefur einhver þátttakandi hætt í eftirfylgd af einhverjum ástæðum. Kaplan-Meier metilinn er bara metinn á þeim tímapunktum sem atburðir eiga sér stað, svo grafið breytist ekki á þeim tímapunktum sem skerðingar eiga sér stað. Sum tímarit kjósa að fá Kaplan-Meier gröf með slíkum merkingum þegar skerðingar eru en önnur ekki. Það er ætíð hægt að stilla til í R (nota censor = FALSE í ggsurvplot).</p>
<p>Skoðun nú Kaplan Meier gröfin eftir persónuleikagerð. Breytum skalanum aftur í ár.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="lif.html#cb26-1"></a>km.plot &lt;-<span class="st"> </span><span class="kw">ggsurvplot</span>(KM_<span class="dv">1</span>,<span class="dt">risk.table =</span> T,</span>
<span id="cb26-2"><a href="lif.html#cb26-2"></a>                        <span class="dt">break.time.by=</span><span class="dv">1</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="fl">0.8</span>,<span class="dv">1</span>),<span class="dt">tables.height=</span><span class="fl">0.3</span>) </span>
<span id="cb26-3"><a href="lif.html#cb26-3"></a>km.plot</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Á þessari mynd virðist vera mikill munur á tíðni hjartasjúkdóma eftir persónuleikagerð. Rauði ferillinn, sem táknar persónuleikagerð A, er allur fyrir neðan bláa ferilinn sem táknar persónuleikagerð B. Þar af leiðandi metum við að lifunarfallið sé lægra, þ.e. að líkur þess að vera <strong>án</strong> hjartasjúkdóms eru minni, sem þýðir að líkurnar á því að <strong>fá</strong> hjartasjúkdóm eru hærri.</p>
</div>
<div id="log-rank-próf" class="section level3" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Log-rank próf</h3>
<p>Nú skoðum við hvort sá munur á tíðni hjartasjúkdóma eftir persónuleikagerðunum sem við sáum bæði með Kaplan Meier metlinum og í Kaplan Meier grafinu sé tölfræðilega marktækur en allt bendir til þess að svo sé. Ein leið til að prófa þann mun er með <strong>log-rank prófi</strong> en það prófar hvort munur sé á tveimur lifunarföllum. Skipunin sem við notum er <span class="math inline">\(survdiff\)</span> og er úr <span class="math inline">\(survival\)</span> pakkanum.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="lif.html#cb27-1"></a><span class="kw">survdiff</span>(<span class="kw">Surv</span>(surv_time_y, status) <span class="op">~</span><span class="st"> </span>dibpat, <span class="dt">data =</span> wcgs_dat)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(surv_time_y, status) ~ dibpat, data = wcgs_dat)
## 
##             N Observed Expected (O-E)^2/E (O-E)^2/V
## dibpat=A 1583      177      125      21.3      41.9
## dibpat=B 1557       78      130      20.6      41.9
## 
##  Chisq= 41.9  on 1 degrees of freedom, p= 9e-11</code></pre>
<p>Munurinn reyndist marktækur, p-gildið er <span class="math inline">\(1 \cdot 10^{-10}\)</span>. Logrank prófið er líka hægt að nota þegar hóparnir eru fleiri en tveir og prófa það þá núlltilgátuna hvort allir ferlarnir séu eins.</p>
<p>Núlltilgátan er að atburðir séu jafn tíðir milli hópanna. Taflan sýnir <em>Expected</em> eða væntanlegan fjölda miðað við þá tilgátu. En gögnin sýna (<em>Observed</em>) að atburðir eru færri í B hóp og fleiri í A hóp en búast mætti við ef tilgátan væri sönn. Við höfnum þeirri tilgátu og drögum þá ályktun að tíðni atburða sé meiri í A hóp.</p>

</div>
</div>
<div id="prof_haz" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Hlutfallsleg áhætta</h2>
<p>Log-rank prófið segir okkur bara að munur sé á lifun milli hópa en ekki hve mikill hann er. Í log-rank prófinu er hægt að leiðrétta með því að gera stratified próf en það er ekki hægt að leiðrétta fyrir samfelldum breytum. Það er aftur á móti hægt í Cox líkaninu sem er aðhvarfsgreiningarlíkan. Við viljum færa okkur yfir í afhvarfsgreiningu til að meta áhrifsstærðir og til að geta leiðrétt fyrir skýribreytum (e. explanatory variables).</p>
<p>Cox líkanið felur í sér hlutfallslega áhættu á tímabili sem er til skoðunar.<br />
Látum <span class="math inline">\(h_0(t)\)</span> vera hættufall viðmiðunarhóps og <span class="math inline">\(h_1(t)\)</span> vera hættufall meðferðarhóps. Ef áhættuhlutfallið er hlutfallslega jafnt gildir</p>
<p><span class="math display">\[
h_1(t) = \exp(\beta)h_0(t).
\]</span></p>
<p>Þá gildir líka með því að heilda báðum megin að
<span class="math display">\[
H_1(t) = \exp(\beta)H_0(t).
\]</span></p>
<p>Hér er <span class="math inline">\(H_i(t)\)</span> uppsafnaða hættufallið þ.e. <span class="math inline">\(H(t) = \int_0^t h_i(u)du\)</span>,</p>
<p>Notum svo logra báðum megin. Þá fæst</p>
<p><span class="math display">\[
\log(H_1(t)) = \beta + \log(H_0(t)).
\]</span>
Með öðrum orðum: ef hlutfallsleg áhætta gildir er mismunur í logranum af uppsafnaða hættufallinu fasti á milli hópa. Fastinn er logrinn af hættuhlutfallinu.</p>
<p>Mynd af <span class="math inline">\(\log(H_i(t))\)</span> á móti <span class="math inline">\(t\)</span> gefur þá hugmynd um hvor hlutfallslega áhætta sé gild forsenda. Reyndar er betra að teikna á móti <span class="math inline">\(\log(t)\)</span> til að teygja á tímaásnum. Það gefur skýrari mynd. Svo má rifja upp að uppsafnaða hættufallið er sama og logrinn af lifunarfallinu með neikvæðu formerki þ.e.</p>
<p><span class="math display">\[
H_i(t) = -\log(S_i(t)).
\]</span>
Þá má skrifa:</p>
<p><span class="math display">\[
\log(-\log(S_1(t))) = \beta + \log(-\log(S_0(t))).
\]</span>
Þess vegna er mjög algengt að skoða þessa ákveðnu vörpun af lifunarfallinu þ.e. <span class="math inline">\(y \to log(-log(y))\)</span>. Hún hefur sérstakt nafn í R og kallast <em>cloglog</em> fyrir <em>complementary log-log transformation</em>. Í <span class="math inline">\(survival\)</span> pakkanum er hægt að meta lifunarföllin með aðferð Kaplan Meier og bera þau svo saman með <em>cloglog</em> vörpum sem er þá samanburður á logranum af uppsafnaða hættufallinu. Fast bil ætti að vera á milli þeirra eins og kom fram að ofan. Þegar þessi vörpun er valin gildir sjálfkrafa að tímaásinn er á logra skala.</p>
<p>Nú skoðum við gögnin okkar henti fyrir Cox-líkan óbreytt eða hvort við þurfum að leiðrétta fyrir því að hlutfallslega áhætta gildir ekki. Skoðum gögnin í dögum.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="lif.html#cb29-1"></a>KM_<span class="dv">1</span>_day &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(surv_time, status) <span class="op">~</span><span class="st"> </span>dibpat, <span class="dt">data =</span> wcgs_dat)</span></code></pre></div>
<p>Teiknum fyrst lifunargröfin:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="lif.html#cb30-1"></a><span class="kw">plot</span>(KM_<span class="dv">1</span>_day,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="fl">0.8</span>,<span class="dv">1</span>),<span class="dt">col =</span> <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Teiknum næst áhættuna <span class="math inline">\(F_i(t)=1-S_i(t)\)</span>. Það er gert með valinu <em>fun=“event”</em> til að nota vörpunina <span class="math inline">\(y \to 1-y\)</span> á lifunarfallið.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="lif.html#cb31-1"></a><span class="kw">plot</span>(KM_<span class="dv">1</span>_day,<span class="dt">fun=</span><span class="st">&quot;event&quot;</span>,<span class="dt">col =</span> <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Biðjum næst um uppsöfnuðu hættuföllin og notum þá vörpunina <span class="math inline">\(y \to -log(y)\)</span> á lifunarföllin því <span class="math inline">\(H_i(t) = -\log(S_i(t))\)</span>. Þetta er svo algengt að sú vörpun fær nafnið <em>cumhaz</em> í lifunar pakkanum.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="lif.html#cb32-1"></a><span class="kw">plot</span>(KM_<span class="dv">1</span>_day,<span class="dt">fun=</span><span class="st">&quot;cumhaz&quot;</span>,<span class="dt">col=</span><span class="dv">2</span><span class="op">:</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Takið eftir að hér er ekki mikill munur á <span class="math inline">\(1-S_i(t)\)</span> og <span class="math inline">\(-log(S_i(t))\)</span> vegna þess að</p>
<p><span class="math display">\[
-log(S_i(t))=-\log(1-(1-S_i(t))) \approx 1-S_i(t)
\]</span>
ef <span class="math inline">\(1-S_i(t)\)</span> er nálægt því að vera 0 þ.e. ef <span class="math inline">\(S_i(t)\)</span> er nálægt því að vera 1.</p>
<p>Dæmi: Ef <span class="math inline">\(S(t)=0.85\)</span> er <span class="math inline">\(1-S(t)=0.15\)</span> og <span class="math inline">\(-\log(0.85)=0.16\)</span>. Þetta byggir á Taylor nálgun þar sem <span class="math inline">\(log(1-x) \approx -x\)</span> fyrir <span class="math inline">\(x\)</span> nálægt 0.</p>
<p>Að lokum veljum við <em>cloglog</em> vörpunina sem við höfum mestan áhuga á ef við viljum meta hvort hlutfallsleg áhætta gildir.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="lif.html#cb33-1"></a><span class="kw">plot</span>(KM_<span class="dv">1</span>_day,<span class="dt">fun=</span><span class="st">&quot;cloglog&quot;</span>,<span class="dt">col=</span><span class="dv">2</span><span class="op">:</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-18-1.png" width="672" />
Þetta er líka hægt að gera í <span class="math inline">\(survminer\)</span> pakkanum:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="lif.html#cb34-1"></a><span class="kw">ggsurvplot</span>(KM_<span class="dv">1</span>_day,<span class="dt">fun=</span><span class="st">&quot;cloglog&quot;</span>,<span class="dt">risk.table =</span> T,<span class="dt">tables.height =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-19-1.png" width="672" />
Það eru fáir atburðir fyrstu 300 dagana. En eftir það virðist fast bil vera á milli lograna af uppsöfnuðu hættuföllunum. En þau færast samt nær. Það er ekki alveg fullkomlega fast hættuhlutfall, en nógu nálægt því til þess að gera ráð fyrir að hlutfallslega áhætta gildir og beita Cox-líkaninu á óbreytt gögnin.</p>
<p>Skoðum einnig <em>BMI</em> eftir að það er búið að skipta henni í þriðjunga og gera hana að flokkaðri skýribreytu:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="lif.html#cb35-1"></a>KM_<span class="dv">1</span>_bmi &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(surv_time, status) <span class="op">~</span><span class="st"> </span>bmiq3, <span class="dt">data =</span> wcgs_dat)</span></code></pre></div>
<p>Skoðum áhættuföllin:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="lif.html#cb36-1"></a><span class="kw">plot</span>(KM_<span class="dv">1</span>_bmi ,<span class="dt">fun =</span> <span class="st">&quot;event&quot;</span>,<span class="dt">col=</span><span class="dv">2</span><span class="op">:</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Svp látum við duga að skoða <em>cloglog</em> grafið:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="lif.html#cb37-1"></a><span class="kw">ggsurvplot</span>(KM_<span class="dv">1</span>_bmi ,<span class="dt">fun=</span><span class="st">&quot;cloglog&quot;</span>,<span class="dt">risk.table =</span> T,<span class="dt">tables.height =</span> <span class="fl">0.35</span>)</span></code></pre></div>
<pre><code>## Warning: Vectorized input to `element_text()` is not officially supported.
## Results may be unexpected or may change in future versions of ggplot2.</code></pre>
<p><img src="BOK_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="lif.html#cb39-1"></a><span class="kw">plot</span>(KM_<span class="dv">1</span>_bmi,<span class="dt">fun=</span><span class="st">&quot;cloglog&quot;</span>,<span class="dt">col=</span><span class="dv">2</span><span class="op">:</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Gröfin eru nokkuð samsíða eftir tímann 900. Það hafa mjög fáir atburðir gerst fyrir þann tíma. Svo hlutfallslega áhætta virðist líka gilda fyrir BMI.</p>

</div>
<div id="cox" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Cox líkanið</h2>
<p>Cox kom með ákveðna aðferð til að smíða likelihood fall fyrir lifunargreiningu, sjá:</p>
<p>Cox, David R (1972). “Regression Models and Life-Tables”. Journal of the Royal Statistical Society, Series B. 34 (2): 187–220.</p>
<p>Aðferðin fellst í því að nota líkan fyrir hættufallið <span class="math inline">\(h(t)\)</span> út frá skýribreytum þannig að grunn-hættufallið (basline hazard) er margfaldað með línulegri samantekt af skýribreytum með veldis-tengifalli.</p>
<p><span class="math display">\[
h(t) = h_0(t) \exp(\beta_1 x_1 + \cdots + \beta_p x_p),
\]</span>
Athugið að þegar allar skýribreytur eru með gildið 0 þá er <span class="math inline">\(h(t) = h_0(t)\)</span>. M.ö.o. grunn-hættufallið fæst með því að stilla allar skýribreytur á 0 (Því er oft gott að draga meðaltalið frá gildunum eins og við gerðum fyrir aldur).</p>
<p>Takið svo eftir að logrinn af hættuhlutfallinu er línuleg samantekt af skýribreytum.</p>
<p><span class="math display">\[
\log \left( \frac{h(t)}{h_0(t)} \right) = \beta_1 x_1 + \cdots + \beta_j x_j + \cdots + \beta_p x_p.
\]</span></p>
<p>Hækkum nú <span class="math inline">\(x_j\)</span> um eina einingu og skrifum</p>
<p><span class="math display">\[
\log \left( \frac{h&#39;(t)}{h_0(t)} \right) = \beta_1 x_1 + \cdots + \beta_j ( x_j+1) + \cdots + \beta_p x_p.
\]</span>
þar sem <span class="math inline">\(h&#39;\)</span> táknar hér hættufallið miðað við að <span class="math inline">\(x_j\)</span> hafi hækkað um eina einingu. Hér er <strong>ekki</strong> verið að diffra, heldur er komman notuð til að merkja <span class="math inline">\(h\)</span>.</p>
<p>Drögum svo vinstri hliðar og hægri hliðar að ofan frá jöfnunni sem við vorum að skrifa. Þá fæst</p>
<p><span class="math display">\[
\log \left( \frac{h&#39;(t)}{h(t)} \right) = \beta_j.
\]</span></p>
<p>Hættuhlutfallið þegar <span class="math inline">\(x_j\)</span> hækkar um eina einingu er þar með <span class="math inline">\(e^{\beta_j}\)</span> eða <span class="math inline">\(\exp(\beta_j)\)</span>. Hefðum við hækkað <span class="math inline">\(x_j\)</span> um <span class="math inline">\(\Delta\)</span> einingar væri hættuhlutfallið <span class="math inline">\(\exp(\Delta \beta_j)\)</span>.</p>
<p>Takið eftir hvernig <span class="math inline">\(h_0\)</span> styttist út í svona útreikningum. Hér notum við að <span class="math inline">\(\log(u) - \log(v) = \log(\frac{u}{v})\)</span> og að</p>
<p><span class="math display">\[
\log(a/c) - \log(b/c) = \log \left(\frac{a}{c} \cdot  \frac{c}{b} \right) = \log \left(\frac{a}{b} \right).  
\]</span></p>
<p>Cox notar svo skilyrt líkindi <span class="math inline">\(P(A|B) = P(A \cap B) / P(B)\)</span> til að búa til hálíknafallið og nýtir sér að <span class="math inline">\(h_0\)</span> styttist út. Við leitum svo með tölulegum aðferðum af því gildi á <span class="math inline">\(\boldsymbol{\beta}\)</span> sem hámarkar það fall. Það er ekkert sem segir að <span class="math inline">\(\boldsymbol{\beta}\)</span> þurfi að vera eins yfir allan tímaskalann.</p>
<p>Cox líkanið er í raun <em>relative risk model</em> og það eru óþarfa hömlur að hugsa um Cox líkanið sem proportional hazards líkan. Það má auðveldlega leyfa áhrifum skýribreytna að breytast í tíma sem og gildunum á þeim.</p>
<p>Við byrjum á því að gera Cox-líkanið fyrir persónuleikagerðirnar án nokkurra frekari skýribreytna. Notum daga sem tímaeiningu.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="lif.html#cb40-1"></a>Cox_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(surv_time, status) <span class="op">~</span><span class="st"> </span>dibpat, <span class="dt">data =</span> wcgs_dat)</span></code></pre></div>
<p>!!! ATH, hvernær notum við ties = “breslow”?</p>
<p>Prófum hvort hlutfallsleg áhætta gildir með því að meta leitnina í hættuhlutfallinu yfir tíma. Ef hlutfallslega áhætta gildir þá ætti beta(t) fallið að vera lárétt lína.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="lif.html#cb41-1"></a>Cox_<span class="fl">1.</span>zph &lt;-<span class="st"> </span><span class="kw">cox.zph</span>(Cox_<span class="dv">1</span>)</span></code></pre></div>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="lif.html#cb42-1"></a><span class="kw">plot</span>(Cox_<span class="fl">1.</span>zph)</span>
<span id="cb42-2"><a href="lif.html#cb42-2"></a><span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">coef</span>(Cox_<span class="dv">1</span>))</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-26-1.png" width="672" />
Leitnin er niður á við þ.e. hættuhlutfallið minnkar með tímanum. Lækkunin er þó ekki marktæk tölfræðilega. Sem staðfestir að okkur er óhætt að nota Cox-líkanið.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="lif.html#cb43-1"></a>Cox_<span class="fl">1.</span>zph</span></code></pre></div>
<pre><code>##        chisq df    p
## dibpat   2.6  1 0.11
## GLOBAL   2.6  1 0.11</code></pre>
<p>!!! ATH, setja frekari útskýringar varðandi myndina og töfluna fyrir ofan.<br />
!!! ATH, þetta er í raun sama myndin en með transform = “rank”, hvaða áhrif hefur það?</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="lif.html#cb45-1"></a>czp_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">cox.zph</span>(Cox_<span class="dv">1</span>,<span class="dt">transform =</span> <span class="st">&quot;rank&quot;</span>)</span>
<span id="cb45-2"><a href="lif.html#cb45-2"></a></span>
<span id="cb45-3"><a href="lif.html#cb45-3"></a><span class="kw">plot</span>(czp_<span class="dv">2</span>)</span>
<span id="cb45-4"><a href="lif.html#cb45-4"></a><span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">coef</span>(Cox_<span class="dv">1</span>))</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Skoðum nú niðurstöðu Cox-líkansins fyrir áhættuhlutfallið og berum saman við fyrri niðurstöður. Samkvæmt Cox er áhættuhlutfallið 0.43 og öryggisbilið ( 0.33, 0.56). Við fengum sama áhættuhlutfall með handreikningi og með því að gera ráð fyrir veldisvísidreifingu. !!! ATH er það rétt skilið hjá mér að það sé ekki rétt að reikna áhættuhlutfall fyrir Kaplan Meier metilinn?</p>
<p>Skoðum núna Cox-líkanið fyrir BMI, getum hérna notað upphaflegu samfelldu breytuna.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="lif.html#cb46-1"></a>Cox_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(surv_time, status) <span class="op">~</span><span class="st"> </span>bmi, <span class="dt">data =</span> wcgs_dat)</span>
<span id="cb46-2"><a href="lif.html#cb46-2"></a>Cox_<span class="dv">2</span></span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(surv_time, status) ~ bmi, data = wcgs_dat)
## 
##      coef exp(coef) se(coef)     z        p
## bmi 15842       Inf     4101 3.863 0.000112
## 
## Likelihood ratio test=14.1  on 1 df, p=0.0001731
## n= 3140, number of events= 255</code></pre>
<p>Prófum hvort hlutfallleg áhætta gildir með því að meta leitnina í hættuhlutfallinu yfir tíma.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="lif.html#cb48-1"></a>Cox_<span class="fl">2.</span>zph &lt;-<span class="st"> </span><span class="kw">cox.zph</span>(Cox_<span class="dv">2</span>)</span>
<span id="cb48-2"><a href="lif.html#cb48-2"></a>Cox_<span class="fl">2.</span>zph</span></code></pre></div>
<pre><code>##           chisq df p
## bmi    4.17e-06  1 1
## GLOBAL 4.17e-06  1 1</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="lif.html#cb50-1"></a><span class="kw">plot</span>(Cox_<span class="fl">2.</span>zph)</span></code></pre></div>
<p><img src="BOK_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>Niðurstaðan er að hlutfallsleg áhætta virðist einnig halda fyrir bmi.</p>
<p>Reyndar er niðurstaðan sú sama fyrir allar helstu breytur í þessu gagnasafni. Sjáum það þegar við gerum Cox-aðhvarfslíkanið með mörgum skýribreytum.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="lif.html#cb51-1"></a>Cox_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(surv_time, status) <span class="op">~</span><span class="st">  </span>agec <span class="op">+</span><span class="st"> </span>cholmmol <span class="op">+</span><span class="st"> </span>sbp10 <span class="op">+</span>smoker <span class="op">+</span><span class="st"> </span>bmi  <span class="op">+</span><span class="st"> </span>dibpat <span class="op">+</span><span class="st"> </span>arcus0  , <span class="dt">data =</span> wcgs_dat)</span>
<span id="cb51-2"><a href="lif.html#cb51-2"></a>Cox_<span class="dv">3</span></span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(surv_time, status) ~ agec + cholmmol + sbp10 + 
##     smoker + bmi + dibpat + arcus0, data = wcgs_dat)
## 
##                 coef  exp(coef)   se(coef)      z        p
## agec       5.719e-02  1.059e+00  1.135e-02  5.040 4.64e-07
## cholmmol   3.234e-01  1.382e+00  4.137e-02  7.817 5.39e-15
## sbp10      1.844e-01  1.202e+00  3.802e-02  4.849 1.24e-06
## smokerYes  6.108e-01  1.842e+00  1.319e-01  4.630 3.66e-06
## bmi        1.015e+04        Inf  4.367e+03  2.325   0.0201
## dibpatB   -6.664e-01  5.135e-01  1.371e-01 -4.861 1.17e-06
## arcus0     2.156e-01  1.241e+00  1.322e-01  1.631   0.1030
## 
## Likelihood ratio test=198.4  on 7 df, p=&lt; 2.2e-16
## n= 3140, number of events= 255</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="lif.html#cb53-1"></a><span class="kw">cox.zph</span>(Cox_<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##           chisq df    p
## agec     1.4371  1 0.23
## cholmmol 0.3531  1 0.55
## sbp10    0.0032  1 0.95
## smoker   0.7884  1 0.37
## bmi      0.0692  1 0.79
## dibpat   2.1032  1 0.15
## arcus0   0.5778  1 0.45
## GLOBAL   5.7704  7 0.57</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="lif.html#cb55-1"></a>cox_<span class="dv">3</span>_coef &lt;-<span class="st"> </span>Cox_<span class="dv">3</span><span class="op">$</span>coefficients</span></code></pre></div>
<p>Öll p-gildin eru vel yfir 0.05 sem bendir til þess að hlutfallsleg áhætta gildir fyrir allar þessar breytur.</p>
<p>Lifunarlíkanið sem við fáum ef við notum allar þessar breytur er <span class="math inline">\(h_{1}(t)=e^{0.0572*agec+0.3234*cholmmol+0.1844*sbp10+0.6108*smoke+1.0154599\times 10^{4}*bmi+-0.6664*dibpat +0.2156*arcus}*h_{0}(t)\)</span> Þar sem <span class="math inline">\(h_{0}(t)\)</span> er hazard-fallið þegar allar samfelldu breyturnar eru 0, sem þýðir að upphaflega aldursbreytan er 46, reykingar og arcus eru nei og hegðunarhópurinn er B.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reg.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BOK.pdf", "BOK.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
